### PR TITLE
Add option to prevent Skim from selecting the text after performing forward search

### PR DESCRIPTION
**Pull request by tsung-ju**

### CODE REVIEW

**Comment by lervag** [comment]
This is probably all good, but since I don't use Macs and have no way of testing it: @clason would you care to help me confirm that this may be a  useful addition?

**Comment by clason** [comment]
I'm afk at the moment, but will check it out when I am back.

**Comment by lervag** [comment]
@clason friendly reminder (you may still be afk, but in case you just forgot)

**Comment by clason** [comment]
Oh, sorry, that completely slipped by me. Looks good to me!

**Pull request closed without merging**
