### PR TITLE
Add tsf for toggling inline vs displayed fractions

### PR DESCRIPTION
**Pull request by lervag**
I've finally made a prototype version of this feature (cf. #1390). It is not going to be perfect (I won't fix all edge cases), but it is probably still not quite ready. Please feel free to test and provide feedback!

It would be good to get some example of inline sentences that does not work as expected. Examples should be given as:

1. A single line of text in which fraction toggle should work.
2. The position in the line where the toggle is activated.
3. The expected result.
4. The observed result.

PS! Sorry for taking so very long to work on this issue! However, I think this should be not so far from finished now.

### CODE REVIEW

**Comment by lervag** [comment]
I'll take the liberty of tagging some possibly interested users:
@nilsbecker @clason @kiryph

**Comment by nilsbecker** [comment]
how do i test this? i clone the repo, switch to the toggle-fractions branch and then? how do i install it in vim?

**Comment by lervag** [comment]
Sorry, should have said! There are multiple ways to do it.

1. If you use vim-plug, then you can use this:

    ```vim
    Plug 'lervag/vimtex', {'branch': 'toggle-fractions'}
    ```

    After the change, you should do `PlugUpdate vimtex` and restart.

2. Go to your vimtex folder, e.g. `cd ~/.vim/bundle/vimtex`, then:

    ```sh
    git pull
    git checkout toggle-fractions

    # To revert, do
    git checkout master
    ```

**Comment by nilsbecker** [comment]
thank -- i use Vundle right now which afaict has no git branch support -- i'll manually switch then

**Comment by nilsbecker** [comment]
preliminary testing: 
`\frac{\alpha}{\mu} ` becomes `(\alpha)/(\mu)` which has superfluous parentheses. 
i'm not sure if this is problematic to fix but a fix would be good.

`\frac{r}{f}` becomes `r/f` which is fine; on the way back that becomes `\frac r f` which i think is valid latex but is not ideal -- if someone wants to extend the numerator or denominator it's probably good to have the curly braces? might come down to taste.

but the most important problem is that sometimes vim freezes for 5s with 100% cpu when i invoke tsd?!

**Comment by nilsbecker** [comment]
`(r+t)/((\mu))` becomes `\frac{r+t}{(\mu})`. notice the swapped parentheses.

**Comment by lervag** [comment]
Thanks for the new cases, I'll look into fixing them. I think it should be possible to cover all of them.

> \frac{r}{f} becomes r/f which is fine; on the way back that becomes \frac r f which i think is valid latex but is not ideal -- if someone wants to extend the numerator or denominator it's probably good to have the curly braces? might come down to taste.

Yes, this is probably a metter of taste. I'll change it back to curly braces,
since that might be more standard. And I agree, it makes it easier to extend.

**Comment by lervag** [comment]
I've pushed an update that should fix the edge cases you've noticed.

**Comment by nilsbecker** [comment]
i've noticed this:
`\frac{\delta_{02}}{\delta_{02} + \delta_{01}}`
becomes 
`(\delta_{02})/(\delta_{02} + \delta_{01})`
which is fine. but the way back works only when the cursor is over the denominator. i was surprised at first but maybe that is actually a feature? it might avoid some complexity in deciding how far the fraction extends?

**Comment by nilsbecker** [comment]
what is the current heuristic to decide how far a denominator extends? if there are parentheses, everything inside them i guess? only `()` or also `[]` and `\{\}` ? if there are no parentheses, the current `W`ord or something fancier?

**Comment by nilsbecker** [comment]
another one:
`\(a/p_\text{b}\)`. this gives
`\(\frac{a}{p_}\text{b}\)` when invoked over `a` or over `p` and does nothing over the subscript

**Comment by lervag** [comment]
Thanks! I think the first issue should be possible to solve, I'll look into it. The latter issue is more difficult.

> what is the current heuristic to decide how far a denominator extends? if there are parentheses, everything inside them i guess? only () or also [] and \{\} ? if there are no parentheses, the current Word or something fancier?

If there are parantheses, I try to match the opening and closing parantheses. This should work well. The problem is in the case where there is no parantheses, such as the last example you provide. Here we need more complex parsing. In particular, we need a smart way to detect that `p_\text{b}` is a single "atom". Currently, I use a simple regex for word characters: `^\s*\\\?\w*`. The problem is that it does not match the super/sub script.

**Comment by nilsbecker** [comment]
hi, i just stumbled upon `f(x+y)/g(z)` which will try to make a fraction out of the arguments of the functions. i think there cannot be a general rule that always works according to the intentions of the writer -- in this case it could be reasonable to treat 1. parentheses 2. stuff outside parentheses that is not separated by space as part of numerator/denominator. but in fact i think a visual mode version of the tsf command could be quite a bit easier: split all of the visual selection on `/` and just take these two parts as num and denom.

**Comment by nilsbecker** [comment]
the heuristic above would mean `f(x)g(y)/h(z)` becomes `\frac{f(x)g(y)}{h(z)}` but that's fine imo.

**Comment by lervag** [comment]
> in this case it could be reasonable to treat 1. parentheses 2. stuff outside parentheses that is not separated by space as part of numerator/denominator

Yes, I agree. This is a reasonable approach. I think it will be very difficult to cover every edge case, and so falling back to a relatively simple heuristic should suffice. We'll make sure to document it well.

> but in fact i think a visual mode version of the tsf command could be quite a bit easier: split all of the visual selection on / and just take these two parts as num and denom.

I agree, but I want that to come after the normal mode version is OK and the current PR is merged.

**Comment by lervag** [comment]
Ok, I've updated again so all tests now pass. I think we are ready for merge, but let me know if you find other edge cases that should be updated. I'll also add some docs before merging.

**Comment by lervag** [comment]
I'm merging this now, since I think it is already useful and it should not break anything. Feel free to open new issues if you find things that should work but doesnt.

Also, feel free to suggest a visual mode version of this; if you do, let me know how you think it should work. E.g. from `$a/b$`, is it enough to assume "split on `/`"?

**Comment by nilsbecker** [comment]
i have used it a few times with success. i think it's already useful.

about visual mode, i think a version that is easy to understand and memorize is indeed 'split the entire selection on `/`'. then user is responsible for selecting something reasonable. 
on the way back, from `\frac{x}{y}`, i'm not sure a visual mode makes much sense?

**Comment by lervag** [comment]
Thanks, I've added a new issue for it (see #1651). Let me know in that thread if you agree with the specification.

**Pull request merged**
