### PR TITLE
Add support for aux_dir for latexmk

### PR DESCRIPTION
**Pull request by lervag**
See discussion in #2534.

This adds a breaking change: `build_dir` is changed to `out_dir` throughout. Thus, anyone who changes the `build_dir` key of e.g. `g:vimtex_compiler_latexmk` will need to update their configuration!

The term "`build_dir`" is not really used in any of the backend compiler tools, so it was probably a mistake to add a new term here. Therefore, as a step towards adding support for `aux_dir` for the latexmk backend, we change `build_dir` to `out_dir`. `out_dir` (or similar variants) is a specific "concept" in both latexmk, latexrun and tectonic.

### CODE REVIEW

**Comment by doronbehar** [comment]
Hey, I am also experiencing perhaps related issues with `build_dir`. I was about to suggest the following PR:

```patch
commit 823c8f4152fb86e549355f401e44ae356b1ded49
Author: Doron Behar <doron.behar@gmail.com>
Date:   Sat May 20 17:48:37 2023 +0300

    Document the real default build_dir compiler option

diff --git a/doc/vimtex.txt b/doc/vimtex.txt
index 0a6bff4e..7fb6b01a 100644
--- a/doc/vimtex.txt
+++ b/doc/vimtex.txt
@@ -962,7 +962,7 @@ OPTIONS                                                        *vimtex-options*
   Default value: >vim
 
     let g:vimtex_compiler_latexmk = {
-        \ 'build_dir' : '',
+        \ 'build_dir' : {-> expand("%:p:h")},
         \ 'callback' : 1,
         \ 'continuous' : 1,
         \ 'executable' : 'latexmk',
```

I took the empty `build_dir` option when I set my `g:vimtex_compiler_tectonic` suggested by the docs and I noticed that `VimtexClean` doesn't work for me because it attempts to clean files in my root directory `/`. Hence the minimum is for the documentation to be correct :).

**Comment by lervag** [comment]
> I took the empty `build_dir` option when I set my `g:vimtex_compiler_tectonic` suggested by the docs and I noticed that `VimtexClean` doesn't work for me because it attempts to clean files in my root directory `/`. Hence the minimum is for the documentation to be correct :).

I agree we should update the docs if they are wrong. However, I don't understand why you claim the docs are wrong. I may just be a tad slow, but as far as I understand, the `'build_dir'` value is an empty string unless it is changed.

Although I see why you find this related, I still find it to be a separate issue. I would therefore prefer if we can continue this discussion in a new thread if you should still think the docs are wrong.

**Comment by tertsdiepraam** [comment]
I'm just passing by, but I ran into a similar problem as mentioned in the issue and wanted to confirm that it was indeed fixed by using this branch. Thank you!

**Comment by lervag** [comment]
I've updated the branch with a force push. Let me know if you need help checking out the updated branch.

**Comment by lervag** [comment]
I'm merging this now. It is a breaking change and I'll make a release to explain necessary steps for those who may be impacted.

**Comment by tyalie** [comment]
Hi sorry for not answering. Needed to recover medically and I found myself in the situation that I wasn't to do what I initially planned to do.

But I've been able to successfully test this PR on the paper that inspired the original issue #2534. Thank you so much for this and investing the time for it

**Comment by lervag** [comment]
> Hi sorry for not answering. Needed to recover medically and I found myself in the situation that I wasn't to do what I initially planned to do.

I'm sorry to hear that and I hope you are doing well, or at least that the outlook is good! <3

> But I've been able to successfully test this PR on the paper that inspired the original issue #2534. Thank you so much for this and investing the time for it

Thank you for the feedback and thank you for pushing me to do this. I believe the changes you've inspired are good and are very sensible.

All the best!

**Pull request closed without merging**
