### PR TITLE
sioyek forward-search column number

### PR DESCRIPTION
**Pull request by JingMatrix**
Well, please don't merge it now; otherwise it will break.
It depends on my pull request https://github.com/ahrm/sioyek/pull/271 , which is waiting for merging.

### CODE REVIEW

**Comment by JingMatrix** [comment]
That request might be hard to merge, but a new request is more likely to be accepted: https://github.com/ahrm/sioyek/pull/273, so I should reopen it.

**Comment by lervag** [comment]
Thanks! I'll look into this when the sioyek PR has been merged; ok?

**Comment by JingMatrix** [comment]
The pull request is merged now, but for stability reason, current pull-request should wait for next release of `sioyek`.

**Comment by lervag** [comment]
Thanks! I noticed that the latest release was in August, which means I should probably have merged this a long time ago. Better late then never, I guess :)

**Pull request closed without merging**
