### PR TITLE
Separate general compiler feature from specific latexmk interface

### PR DESCRIPTION
**Pull request by lervag**
This relates to #651.

Remains:
- [x] Documentation
- [x] Testing

### CODE REVIEW

**Comment by lervag** [comment]
The code passes all the tests (although I should probably add more). It seems to work well on my own projects.

It remains to add documentation, then I'll propose this is merged.

**Comment by lervag** [comment]
@clason says it does not work with `neovim-remote`. Error "E731: dictionary used as string" after `\le`.

**Comment by lervag** [comment]
@clason I'm not quite sure what is wrong now. It works with `vim` and `gvim`. Could you give some more details? E.g., does the error say something about exactly where it fails (you can get the entire error message with `:messages`)? Or could you provide an example of how to reproduce?

**Comment by clason** [comment]
Sure! (not quite) minimal `vimrc`:

```
" mappings for easier movement
let mapleader = ','
let maplocalleader = ','
" plugins via vim-plug
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex', {'for': 'tex'}
call plug#end()
" vimtex settings
let g:tex_flavor='latex'
let g:vimtex_quickfix_warnings = {
            \ 'font' : 0,
            \ 'overfull' : 0,
            \ 'underfull' : 0,
            \ 'packages' : {
            \   'default' : 0,
            \ },
            \}
let g:vimtex_compiler_progname = 'nvr'
```

Minimal `test.tex`:
```
vimrc
\documentclass{article}

\begin{document}

sdfsdf
\sdfsdfs

\end{document}
```

Compiling opens the pdf preview, but not the quickfix list; `VimtexErrors` does open the quickfix list, but not before throwing the error

```
Error in execution of "function 25":
Line 26:
E731: Dictionary used as String
```

**Comment by lervag** [comment]
Thanks! I fixed the quickfix error. It remains to fix the problem with callbacks for neovim. I'll look at it later tonight.

**Comment by clason** [comment]
Nice! Now it works as expected: Quickfix list opens automatically if there's an error or warning. The only possible callback problem I can see is that it doesn't print `compile: success` or `fail`, but that's purely cosmetic.

**Comment by lervag** [comment]
Hm, @clason: See [here](https://github.com/neovim/neovim/issues/5056#issuecomment-290151557): My most recent fix should not be necessary on newer neovim versions. I was curious if it would be bad of me to revert my fix and instead demand that neovim users use a more recent version of neovim?

**Comment by clason** [comment]
Yeah, that issue did sound familiar... But I am using the latest released neovim version (0.1.7) which does not have that change; the new version (0.2.0) is long overdue, but expected Real Soon(tm). But as soon as it is released, I agree that the fix can be reverted.  (And I would even understand if you preferred to avoid the extra code path at the expense of accepting short-term breakage for us early-adopters until the new version is released.)

**Comment by lervag** [comment]
Although I understand it is a little bit annoying, I think I want to allow a short-term breakage. I feel this is more of a bug at neovim, and it feels wrong to add a hack to vimtex when I know that a fix has been merged upstream.

I hope you can live with the minor inconveniance for a little while. This feature hasn't been merged yet either, but I plan to merge this week unless something important/unexpected bad comes up.

It should be pretty easy to workaround, either by disabling the callback, or by manually editing the code.

In any case, the other problem was actually a good catch, because it was a rather important bug. It is fixed now, so everything should work as expected on a recent neovim version now.

**Comment by clason** [comment]
It is a bit (but not very) annoying since I a) completely transitioned to neovim on Linux and b) tend to check in changes before manually checking for errors... But I completely understand, and I appreciate you trying to support neovim as well as vanilla vim. 

Is this something I could fix locally on the vimrc level, short term?

**Comment by lervag** [comment]
You can do this:

```vim

autocmd User VimtexEventInitPost au! vimtex_quickfix_fix_dirs
```

This will remove the autocommand that fixes paths, which might be slightly inconvenient. But most errors should show up correctly, I think. And the error will not be there.

**Comment by clason** [comment]
That's perfectly fine as a workaround until the new version is finally released. Thanks!

**Comment by lervag** [comment]
No problem. I'm happy we found a good compromise here.

I'll merge this PR tomorrow unless there are more comments/issues.

**Pull request merged**
