### PR TITLE
New event: VimtexEventCompileSuccess

### PR DESCRIPTION
**Pull request by pseewald**
As discussed in #1760

### CODE REVIEW

**Comment by lervag** [comment]
Thanks! However, I think the idea is that the event can do everything that the callback hook can and that it may be considered "simpler" and more clean. Thus, I want to make a breaking change and remove the old callback hook. This means a bigger change. I'll work on that myself after merging this. :)

**Comment by lervag** [comment]
I've made the changes now. And, as always, there may be bugs. So don't hesitate to let me know if you find any!

**Comment by pseewald** [comment]
I did not dare to remove callback hook myself, so thank you for taking care of this!

**Comment by lervag** [comment]
I can understand that! :) I made the changes last night and also made some similar changes to other parts. Thanks for the suggestion and contribution!

**Pull request closed without merging**
