### PR TITLE
Feature: Context menu for citations

### LINKED ISSUE #1541: More actions for cite keys (open PDF, open bibentry, ...)
It would be nice if e.g. typing `<cr>` on top of a cite key would open a context menu from which one could choose to open the corresponding PDF, edit the bibentry, etc, depending on what is available. E.g., if the pdf is available through a `file` key of the bibentry, then one could open it. If an url or doi key is available, then one could open this. Else just edit the bibentry.

### PR DESCRIPTION
**Pull request by lervag**
This implements a first version of a context menu for citations, as well as a backend for context menus in general. It should resolve #1541 

Remaining work:

- [x] Clean up commits
- [x] Add documentation
- [x] Possibly: add tests

### CODE REVIEW

**Comment by lervag** [comment]
@jabirali I would love to get feedback from you on this feature. Do you have time to test it?

**Comment by lervag** [comment]
I think this is ready to be merged, but I'd like some opinions/thoughts first. Anyone interested in testing it?

@clason @Konfekt @jabirali @Rmano

**Comment by lervag** [comment]
(I'm currently using this myself while working on a review paper, and I already find this to be very useful!)

**Comment by Rmano** [comment]
Although I am quite busy now I have to review a student's paper so I could try... ¿do you have any "fast hint" on how to switch branches to a PR? I use [vim-plug](https://github.com/junegunn/vim-plug)... with a safe way of going back, I mean ;-)

**Comment by clason** [comment]
Just go to the plugin directory, `git fetch --all; git checkout feat/context`. To return, `git checkout master` (or just do `PlugUpdate).

**Comment by Konfekt** [comment]
> Although I am quite busy now I have to review a student's paper so I could try... ¿do you have any "fast hint" on how to switch branches to a PR? I use [vim-plug](https://github.com/junegunn/vim-plug)... with a safe way of going back, I mean ;-)

@Rmano Try

```vim
Plug 'https://github.com/lervag/vimtex/pull/1802', { 'branch': 'feat/context' }
```

**Comment by clason** [comment]
@lervag That's pretty neat! I -- extensively! -- use texlab LSP for Edit/Show Entry, so can attest to the usefulness. (If you want to be really fancy for bonus points, you can make Show Entry first transform the Entry into markdown.)

I don't have local `file` entries in my bibfiles (too much collaborative work), the Open DOI is nice indeed.

**Comment by Rmano** [comment]
When it works is ok --- although I think I have some fun settings, looks like this:

image

The problem is that most of the time I have a "cite key now found", like: 

image

But the key is in the bib file, it comes out correctly: 

```bash
[romano:~/research … eh/SoA-sensor-subm2] % grep CALOZ2006 biblio.bib 
@incollection{CALOZ2006,
```

**Comment by clason** [comment]
@Rmano the first picture looks correct (or at least the same as I get) -- what is funny about it?

For the second picture, what springs to mind is that it might be a parsing problem due to the `}}` -- can you test with `\cite{CALOZ2006} }` (extra space between braces)?

**Comment by Rmano** [comment]
> For the second picture, what springs to mind is that it might be a parsing problem due to the `}}` -- can you test with `\cite{CALOZ2006} }` (extra space between braces)?

No, same thing. Now, the bib file is a mess (the student did not really understand the format yet), so it could be this...

**Comment by Rmano** [comment]
I think the first entry that mess up the search is this:

```
@inbook{doi:10.1002/9780470191736.ch1,
```

So not a parenthesis, maybe the `/`?

**Comment by clason** [comment]
No, that can't be it; the same bibkey works for me.

**Comment by lervag** [comment]
It would suffice to share the bib entry. I suspect there's a syntax error.

ons. 23. sep. 2020, 18:01 skrev Romano Giannetti <notifications@github.com>:

**Comment by Rmano** [comment]
Ok: 

```
@inbook{doi:10.1002/9780470191736.ch1,
author = { Ricardo Marqués
and Ferran Martín
and Mario Sorolla},
publisher = {John Wiley {\&} Sons, Ltd},
isbn = {9780470191736},
title = {The Electrodynamics of Left-Handed Media},
booktitle = {Metamaterials with Negative Parameters},
chapter = {1},
pages = {1-41},
doi = {10.1002/9780470191736.ch1},
url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/9780470191736.ch1},
eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/9780470191736.ch1},
year = {2007},
keywords = {solid-state plasmas, negative refractive index, backward cerenkov radiation},
abstract = {Summary This chapter contains sections titled: Introduction Wave Propagation in Left-Handed Media Energy Density and Group Velocity Negative Refraction Fermat Principle Other Effects in Left-Handed Media Waves at Interfaces Waves Through Left-Handed Slabs Slabs with ϵ/ϵ0 → − 1 and µ/µ0 → − 1 Losses and Dispersion Indefinite Media Problems References},
}
```

**Comment by Rmano** [comment]
But I am not really sure it is it --- it's an huge bib file, not all entries are used, and I am preparing tomorrow's beamer presentation ;-P

**Comment by Rmano** [comment]
When is the bib file read? I mean, if I change the bib file do I need to reload the .tex file to check or not? I am suspecting the strange unicode chars in the entry...

**Comment by Rmano** [comment]
> When is the bib file read? I mean, if I change the bib file do I need to reload the .tex file to check or not? I am suspecting the strange unicode chars in the entry...

No, it seems that that entry is not the culprit.

**Comment by Rmano** [comment]
> @Rmano the first picture looks correct (or at least the same as I get) -- what is funny about it?

Nothing, sorry, got confused --- I was expecting a pop-up similar to completion

**Comment by Rmano** [comment]
Another thing: if I press return with the cursor on `\cite{Javier1, Javier2}`, wherever I am, I get the first cite only.

**Comment by lervag** [comment]
> @lervag That's pretty neat! I -- extensively! -- use texlab LSP for Edit/Show Entry, so can attest to the usefulness. (If you want to be really fancy for bonus points, you can make Show Entry first transform the Entry into markdown -- maybe as a separate Preview Entry option.)

Yes, definitely, that's on my TODO list. Or, at least, I want to convert it to something that is easier to read. Not sure if Markdown is the better option? Perhaps yaml is better?

> Any plans of supporting popups as a UI? (I understand that the divergent API in vim and neovim would make this a pain...)

Actually, yes. But that's for the next step. I don't know exactly how to do it yet, and I also need to figure out how that would work. Examples and ideas are appreciated!

> I did notice that the DOI parser has problems with entries containing parentheses (yes, that _does_ happen in practice, e.g. `https://doi.org/10.1016/S0924-6509(09)70252-1`).

Could you provide a full example?

> Another thing: if I press return with the cursor on \cite{Javier1, Javier2}, wherever I am, I get the first cite only.

This works as expected for me. Strange.

> The problem is that most of the time I have a "cite key not found", like:
> ...

Ok, so, for the strange problems with your bib file: the bib entry seems to work fine for me, so it must be something else. Perhaps the easiest is if you could send it to me (that is, if you don't mind sharing it)?

> Going back to work, promise:-P

Famous last words... :)

**Comment by lervag** [comment]
> > Another thing: if I press return with the cursor on \cite{Javier1, Javier2}, wherever I am, I get the first cite only.
> 
> This works as expected for me. Strange.

Ah, it works when there are no spaces. Are spaces allowed here?

**Comment by clason** [comment]
> Yes, definitely, that's on my TODO list. Or, at least, I want to convert it to something that is easier to read. Not sure if Markdown is the better option? Perhaps yaml is better?

It should be human-readable, not meant for further processing, so I'd suggest markdown -- or even plain text (or conceal?).

Here's what nvim-lsp/texlab do (and a shameless showing off...):
Screenshot 2020-09-23 at 18 40 49

> Actually, yes. But that's for the next step. I don't know exactly how to do it yet, and I also need to figure out how that would work. Examples and ideas are appreciated!

Makes total sense. I know you want to keep this vim/neovim compatible, but https://github.com/nvim-lua/telescope.nvim is starting to evolve into something like an UI framework.

There is also work on adding a vim compatible popup-UI for neovim (https://github.com/nvim-lua/popup.nvim), but that one is early days still... (Just something to keep an eye on.)

**Comment by Rmano** [comment]
> > @lervag That's pretty neat! I -- extensively! -- use texlab LSP for Edit/Show Entry, so can attest to the usefulness. (If you want to be really fancy for bonus points, you can make Show Entry first transform the Entry into markdown -- maybe as a separate Preview Entry option.)
> 
> Yes, definitely, that's on my TODO list. Or, at least, I want to convert it to something that is easier to read. Not sure if Markdown is the better option? Perhaps yaml is better?
> 
> > Any plans of supporting popups as a UI? (I understand that the divergent API in vim and neovim would make this a pain...)
> 
> Actually, yes. But that's for the next step. I don't know exactly how to do it yet, and I also need to figure out how that would work. Examples and ideas are appreciated!
> 
> > I did notice that the DOI parser has problems with entries containing parentheses (yes, that _does_ happen in practice, e.g. `https://doi.org/10.1016/S0924-6509(09)70252-1`).
> 
> Could you provide a full example?
> 
> > Another thing: if I press return with the cursor on \cite{Javier1, Javier2}, wherever I am, I get the first cite only.
> 
> This works as expected for me. Strange.
> 
> > The problem is that most of the time I have a "cite key not found", like:
> > ...
> 
> Ok, so, for the strange problems with your bib file: the bib entry seems to work fine for me, so it must be something else. Perhaps the easiest is if you could send it to me (that is, if you don't mind sharing it)?
> 
> > Going back to work, promise:-P
> 
> Famous last words... :)

Yes, no problem. I prefer email, if possible, to avoid having it linked here forever...

**Comment by Rmano** [comment]
> Ah, it works when there are no spaces. Are spaces allowed here?

Well, they do work ;-) at least in IEEEarticle...

**Comment by lervag** [comment]
@clason

> It should be human-readable, not meant for further processing, so I'd suggest markdown -- or even plain text (or conceal?).

I think it is better now. But do you want something more like in a real reference style? I prefer it to show what is available in the entry.

> Here's what nvim-lsp/texlab do (and a shameless showing off...): ...

Interesting! It seems your [doi doesn't work](https://dx.doi.org/10.1007/978-3-030-52784-6)..? :)

> Makes total sense. I know you want to keep this vim/neovim compatible, but https://github.com/nvim-lua/telescope.nvim is starting to evolve into something like an UI framework.
> 
> There is also work on adding a vim compatible popup-UI for neovim (https://github.com/nvim-lua/popup.nvim), but that one is early days still... (Just something to keep an eye on.)

Thanks for the links. I'll look into it, if only to be inspired. As you've noted, I want to keep this Vim+neovim compatible, and so I won't rely on neovim only backends. I also prefer to keep vimtex "dependency free" (at least with respect to other Vim plugins). So if I can solve things with not too much code, I'll just implement it myself.

@Rmano

> Yes, no problem. I prefer email, if possible, to avoid having it linked here forever...

No problem. My email should not be a secret, I think... (it's all over the vimtex git history).

> > Ah, it works when there are no spaces. Are spaces allowed here?
> 
> Well, they do work ;-) at least in IEEEarticle...

And not they work here. :)

**Comment by clason** [comment]
> I think it is better now. But do you want something more like in a real reference style? I prefer it to show what is available in the entry.

Oh, yes, that's very nice! I agree that seeing all entries as they appear in the bib is useful (I use "peek definition" from LSP for that) -- I think you've hit on a very good compromise there; I don't see a need for a further "show as it would be printed" option.

> Interesting! It seems your [doi doesn't work](https://dx.doi.org/10.1007/978-3-030-52784-6)..? :)

No, that'd have been too much of a `#ad` ;) (Publishing date got delayed a bit for obvious reasons. If someone is really interested, Google will find it at the publisher's site.)

> Thanks for the links. I'll look into it, if only to be inspired. As you've noted, I want to keep this Vim+neovim compatible, and so I won't rely on neovim only backends. I also prefer to keep vimtex "dependency free" (at least with respect to other Vim plugins). So if I can solve things with not too much code, I'll just implement it myself.

Makes total sense (some of it may upstream into neovim core; I'll let you know if and when that happens).

**Comment by Rmano** [comment]
> No problem. My email should not be a secret, I think... (it's all over the vimtex git history).

You've got an email ;-)

**Comment by lervag** [comment]
> > I think it is better now. But do you want something more like in a real reference style? I prefer it to show what is available in the entry.
> 
> Oh, yes, that's very nice! I agree that seeing all entries as they appear in the bib is useful (I use "peek definition" from LSP for that) -- I think you've hit on a very good compromise there; I don't see a need for a further "show as it would be printed" option.

Great, I'm happy to hear you agree this is a good compromise.

> > Interesting! It seems your [doi doesn't work](https://dx.doi.org/10.1007/978-3-030-52784-6)..? :)
> 
> No, that'd have been too much of a `#ad` ;) (Publishing date got delayed a bit for obvious reasons. If someone is really interested, Google will find it at the publisher's site.)

Haha, OK. In any case, congrats on publishing the book, it looks interesting!

> Makes total sense (some of it may upstream into neovim core; I'll let you know if and when that happens).

Great, thanks!

@Rmano You've got a reply :)

**Comment by lervag** [comment]
So, it seems to me things work quite well. @Rmano has showed me by example that the bib file parser does not work flawlessly, especially on "unstructured" bib files. In particular, it does not handle the case when a bib entry is written entirely on a single line. I think this can be fixed, though, if someone feels it is important.

**Comment by Rmano** [comment]
>  In particular, it does not handle the case when a bib entry is written entirely on a single line. I think this can be fixed, though, if someone feels it is important.

Citing my email answer, I think I can live with it.

The "bad" entries come out from probably bad Windows->Mac->sane (oops, Unix) line endings when pasting in overleaf.

Yes, it's reasonable to ask for a minimum formatted bib file. Just put it on the FAQ (maybe a hint on the error message too to look at the FAQ), because otherwise, you'll have a lot of issues raised ;-)

**Comment by lervag** [comment]
> > In particular, it does not handle the case when a bib entry is written entirely on a single line. I think this can be fixed, though, if someone feels it is important.
> 
> Citing my email answer, I think I can live with it.

Well, I realized this was already almost there, so I just fixed it. Let me know if you find more examples where the vimtex bib parser does not work as expected.

**Comment by Rmano** [comment]
Wow, it's just great! It works ok on my test file... nice, for me, it's good to go!

**Comment by lervag** [comment]
And all tests are still passing. I'll merge this, then. Feel free to open new issues and suggestions wrt. the context feature. I've tried to implement this to make it quite easy to add other similar types of context menus as well.

**Pull request closed without merging**
