### PR TITLE
doc: Add nvim-compe to the autocompletion section

### PR DESCRIPTION
**Pull request by savq**
Following [this reddit thread](https://www.reddit.com/r/neovim/comments/o1gcwt/is_it_possible_to_add_the_vimtex_completion_in/), this PR adds some information on how to use VimTeX with nvim-compe.

I didn't find info on whether compe can use regex patterns for filetypes 😕 but I followed u/mybumsonfire advice on adding the filetype explicitly.

I added a code sample in Lua, though another one in Vimscript can also be added.

I'm glad VimTeX is so well documented 👍

### CODE REVIEW

**Comment by jdhao** [comment]
I am writing just to confirm that @savq has provided the correct config (which the original reddit post is not).  The value for the key `filetypes` should be a list, not string. My working config for nvim-come (in lua):

```
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'always';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    omni = {filetypes = {'tex'}};
    path = true;
    buffer = true;
    spell = {filetypes = {'markdown', 'tex'}};
    emoji = true;
    nvim_lsp = true;
    nvim_lua = true;
    ultisnips = true;
    calc = false;
    vsnip = false;
  };
}
```

**Comment by lervag** [comment]
> Following [this reddit thread](https://www.reddit.com/r/neovim/comments/o1gcwt/is_it_possible_to_add_the_vimtex_completion_in/), this PR adds some information on how to use VimTeX with nvim-compe.

Thank you!

> I'm glad VimTeX is so well documented +1

Yes, I think it's important to aim for good documentation, especially considering the size of the plugin. And help from people like you is therefore very useful!

> I am writing just to confirm that @savq has provided the correct config (which the original reddit post is not).

Thanks! Also thanks for the references to relevant issues!

----

One open question remains: Is there something in nvim-compe that is equivalent to the `input_patterns` variable in deoplete/neocomplete, or the `complete_pattern` in ncm2?

**Comment by savq** [comment]
> One open question remains: Is there something in nvim-compe that is equivalent to the input_patterns variable in deoplete/neocomplete, or the complete_pattern in ncm2?

@lervag, compe seems to be able to use regex patterns for the buffer source, but not for omni-completion. The default pattern matches alphanumeric words, including kebab-case: `\h\w*\%(-\w*\)*`. [The docs](https://github.com/hrsh7th/nvim-compe/blob/d0934e7b335283879fd3e4ca68adaee6a92688b0/doc/compe.txt#L243) mention it's an experimental feature.

**Comment by lervag** [comment]
Ok, thanks. If something like that should be implemented, then feel free to notify me and/or suggest an update to the configuration suggestions in the docs.

**Pull request merged**
