### PR TITLE
Add a new bib parser written in Lua

### PR DESCRIPTION
**Pull request by lervag**
Adding a lua parser for bibtex files.

See #2786.

### CODE REVIEW

**Comment by micangl** [comment]
I think there may be an issue. When testing this commit, I've noticed that the time it took for the context-menu to show up wasn't significantly lower. I've tried setting the `g:vimtex_parser_bib_backend` option to alternative with values, but to no avail: the time efficiency was always the same.

When debugging I've seen that, in practically all calls to the `vimtex#parse#bib` function, the argument `{ 'backend': 'vim'}` is provided, effectively voiding the influence of the global backend option.

Also, in the `lua/vimtex/bibparser.lua` file, `M.parse` function, line 230, the `format_entry` is called on every entry; the goal of said function is to format the results in markdown and improve readability (which I don't think could be called a desired effect here?).

**Comment by lervag** [comment]
Yes, sorry, I didn't update the parser for the context menu yet - I've fixed this locally but not pushed it. Thanks for checking, though! Your too fast for me ;)

**Comment by lervag** [comment]
There, I think these are fixed now.

**Comment by lervag** [comment]
> When debugging I've seen that, in practically all calls to the `vimtex#parse#bib` function, the argument `{ 'backend': 'vim'}` is provided, effectively voiding the influence of the global backend option.

Yes; the reason for this is that the context menu _needs_ the source file and line number entries that we do not get with the bibtex backend. The Vimscript parser was written mostly to support the context menu feature.

**Comment by micangl** [comment]
Ok, I've tested the new commit and everything seems to working well.

**Comment by lervag** [comment]
I've improved the code now. It may not be much faster, but at least it is much easier to understand (IMHO).

**Comment by lervag** [comment]
I think that's about as far as I'll go with this. I'll leave the PR open a few days before merging in case anyone wants to test. But I think it should be fine and that it should provide a nice speedup for some people.

**Comment by lervag** [comment]
Ok, I've merged this now.

Notice that I've made some quite significant changes both to the Lua and the Vimscript parsers. I believe I've fixed some bugs in the process, and you should consider to either directly rely on the new VimTeX parser in cmp-vimtex or copy and adapt it as you see fit.

**Pull request merged**
