### PR TITLE
doc:sumatrapdf: simplify setup of command-line Vim 

### PR DESCRIPTION
**Pull request by Konfekt**

### CODE REVIEW

**Comment by lervag** [comment]
Could you rebase this on top of the recent master?

**Comment by lervag** [comment]
Good, thanks. This was better! Let me know if it is ready from your side.

**Comment by Konfekt** [comment]
Yes, all good to go. If @norbert-op could test it?

**Comment by Konfekt** [comment]
Further modifications after testing on my Windows machine that had even more universal settings, in particular using the exact path to `vim` instead of merely `vim` or `gvim`.

**Comment by lervag** [comment]
Thanks. I'll still hold for a short amount of time in case @norbert-op is interested and able to test this as well. If there are no updates I'll merge by Sunday evening.

**Comment by norbert-op** [comment]
I did some testing and got this working, but not consistently. For some reason when I start up Gvim or Vim with `&shell = powershell` the forward search after compilation doesn't work. But if I run it with the default shell then switch to PowerShell, it does work.

I do still have to specify `--servername gvim` to get reverse search from Vim in the terminal. Another strange problem, which I can put in a separate bug report if you want, is that a file name with spaces creates empty buffers from reverse search. So if you copy the file and rename it `minimal minimal.tex` reverse search generates an empty file in a new buffer called `minimal`. On other documents I've had one empty buffer created for each space-separated word. This happens even with Command Prompt as the shell.

I'm using vim-plug now, which isn't compatible with PowerShell. I made a toggle to go between shells when I want to install or update a plugin, which is working. When I use my toggle function after starting Vim with default settings, then compile the document, forward search for Vimtex works. I can't figure out what the difference in when I setting the shell, since I checked the relevant variables. I get the same result if I just set the values that are inside `PowerShellOn()` directly in the Vimrc instead of calling them with the function.

Here are my minimal.vim and minimal.tex, run on Windows 8.1 with PowerShell 4. I also tried PowerShell 6.2.3 (pwsh instead of powershell) and didn't see any difference. What do you recommend?

## minimal.vim
```vim
set nocompatible
filetype plugin indent on
syntax on

call plug#begin('~/vimfiles/allpluggedin')
    Plug 'lervag/vimtex'
 call plug#end()

function! PowerShellOn()
	set shell=powershell
	let &shellcmdflag = '-NoProfile -NoLogo -ExecutionPolicy RemoteSigned -Command'
	set shellxescape= shellquote= noshellslash
	let &shellredir = '| Out-File -Encoding UTF8'
	let &shellpipe = '|'
endfunction

function! CommandPromptOn()
	set shell=$ComSpec
	let &shellcmdflag = "/c"
	let &shellxescape = "\"&|<>()@^"
	let &shellquote = ""
	let &shellpipe = ">%s 2>&1"
	set noshellslash
	let &shellredir = ">%s 2>&1"
endfunction

function! ShellToggle()
	if (&shell ==# 'C:\Windows\system32\cmd.exe')
	    call PowerShellOn()
	else
	    call CommandPromptOn()
	endif
endfunction

command ShellToggle :call ShellToggle()

" call ShellToggle()

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . ' -inverse-search "' . exepath(v:progpath)
      \ . ' --servername ' . v:servername . ' +%l "%f"'
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
      \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```
## minimal.tex
```tex
\documentclass{article}

\begin{document}
	This is my minimal .tex example.
	\newpage
	Here's a second page of text.
\end{document}
```

**Comment by Konfekt** [comment]
> I did some testing and got this working, but not consistently. For some reason when I start up Gvim or Vim with &shell = powershell the forward search after compilation doesn't work. But if I run it with the default shell then switch to PowerShell, it does work.

It seems as the  general viewer is called without intermediary switching to `cmd`. This is strange, as 
```vim
" autoload/vimtex/view/general.vim (line 37)
function! s:general.view(file) dict abort " {{{1
```
does all of this, calling
```vim
" autoload/vimtex/view/general.vim (line 70)
let self.process = vimtex#process#start(l:cmd, {'silent': 0})
```

Perhaps a preceding space in `let &shellcmdflag = ' -NoProfile -NoLogo -ExecutionPolicy RemoteSigned -Command'  helps in the meanwhile?

> I do still have to specify --servername gvim to get reverse search from Vim in the terminal. 
Yes, setting a server name in the terminal  is necessary, as documented.

> Another strange problem, which I can put in a separate bug report if you want, is that a file name with spaces creates empty buffers from reverse search. So if you copy the file and rename it minimal minimal.tex reverse search generates an empty file in a new buffer called minimal. On other documents I've had one empty buffer created for each space-separated word. This happens even with Command Prompt as the shell.

Because escaping file names correctly under Windows is complicated, the part ` ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'` takes care of it and in fact `%l "%f"` seems superfluous.
Can you test again removing it, as does the latest commit https://github.com/lervag/vimtex/pull/1529/commits/97206ea16290d7cc5e62368b890bba1fc20d95f9 ?

**Comment by norbert-op** [comment]
I tried incorporating the space before the `&shellcmdflag`, as well as adding a blank space for `&shellxquote` as suggested in https://stackoverflow.com/a/33745531. There's still no forward search when Vim is started with PowerShell, though. Any idea why it would work after starting with cmd.exe and then switching to PowerShell?

```vim
function! PowerShellOn()
	set shell=powershell
	let &shellcmdflag = ' -NoProfile -NoLogo -ExecutionPolicy RemoteSigned -Command'
	set shellxescape= shellquote= noshellslash
	let &shellxquote= ' '
	let &shellredir = '| Out-File -Encoding UTF8'
	let &shellpipe = '|'
endfunction
```

I also removed `%l "%f"` from that line in the SumatraPDF settings but still get the empty buffer `minimal` after reverse search from `minimal minimal.tex`.

**Comment by Konfekt** [comment]
> I also removed %l "%f" from that line in the SumatraPDF settings but still get the empty buffer minimal after reverse search from minimal minimal.tex.

There was still an unescaped file path. Please update according to e19770e8c23c2bbe9379e5b1f0a7c8a46140a9a3

**Comment by lervag** [comment]
@norbert-op @Konfekt Hi gyus, I'm very happy to see the progress here. It seems @Konfekt is adressing the issue and suggesting the updates/fixes for solving it. I don't really have much to add myself, but will keep watching from the sideline.

Note: With `vimtex#process#start` and the `silent` flag turned off, the actual Vim command becomes a `:!` type command. But the shell options should still be temporarily set to their defaults, as far as I can understand. This should also mean that things should work the same regardless of how you change these settings. @norbert-op Do I understand correctly that things still work different depending on how you set these `shell` related options?

**Comment by Konfekt** [comment]
@norbert-op I am not sure why `\%f` and `\%l` are escaped. If things do not work, please also try `%f` and `%l`.

**Comment by norbert-op** [comment]
I'm still getting the same results: starting Vim with `cmd.exe` as shell works after switching to PowerShell, but if I start with PowerShell forward search does nothing. Changing these shell options and the Sumatra options hasn't made a difference so far--perhaps there's some other setting besides these shell variables that is set automatically at startup.

Reverse search creates empty buffers for files with space names with either shell setting.

Here's my updated minimal.vim

```vim
set nocompatible
filetype plugin indent on
syntax on

call plug#begin('~/vimfiles/allpluggedin')
    Plug 'lervag/vimtex'
 call plug#end()

function! PowerShellOn()
	set shell=powershell
	let &shellcmdflag = ' -NoProfile -NoLogo -ExecutionPolicy RemoteSigned -Command'
	set shellxescape= shellquote= noshellslash
	let &shellredir = '| Out-File -Encoding UTF8'
	let &shellpipe = '|'
endfunction

function! CommandPromptOn()
	set shell=$ComSpec
	let &shellcmdflag = '/c'
	let &shellxescape = '\"&|<>()@^'
	let &shellpipe = '>%s 2>&1'
	set noshellslash
	let &shellredir = '>%s 2>&1'
endfunction

function! ShellToggle()
	if (&shell ==# 'C:\Windows\system32\cmd.exe')
	    call PowerShellOn()
	else
	    call CommandPromptOn()
	endif
endfunction

command ShellToggle :call ShellToggle()

call ShellToggle()

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . ' -inverse-search "' . exepath(v:progpath)
      \ . ' --servername ' . v:servername
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':execute ''drop '' . fnameescape(''%f'')^<CR^>'
      \ . ':%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

**Comment by Konfekt** [comment]
Under Windows 10 with Powershell 6.2.2 and
```vim
  let g:vimtex_view_general_viewer = 'SumatraPDF'
  let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . ' -inverse-search "' . exepath(v:progpath) . ' --servername ' . v:servername
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
      \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground(''' . v:servername . ''')^<CR^>^<CR^>\""'
  let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

- without changing the shell settings, or using `cmd` and
```vim
	set shell=$ComSpec
	let &shellcmdflag = '/c'
	let &shellxescape = '\"&|<>()@^'
	let &shellpipe = '>%s 2>&1'
	set noshellslash
	let &shellredir = '>%s 2>&1'
```
works just fine even for file names with spaces.

With
```
	set shell=powershell
	let &shellcmdflag = ' -NoProfile -NoLogo -ExecutionPolicy RemoteSigned -Command'
	set shellxescape= shellquote= noshellslash
	let &shellredir = '| Out-File -Encoding UTF8'
	let &shellpipe = '|'
```
there is an error about a temp file that can't be opened, and `:VimtexView` does nothing.

**Comment by Konfekt** [comment]
As already a simple shell command such as `:%!dir` gives an error about a missing temp file, the `&powershell` configuration 

```vim
	set shell=powershell
	let &shellcmdflag = ' -NoProfile -NoLogo -ExecutionPolicy RemoteSigned -Command'
	set shellxescape= shellquote= noshellslash
	let &shellredir = '| Out-File -Encoding UTF8'
	let &shellpipe = '|'
```
should be fixed first before further debugging.

With the above settings for `cmd`, forward and backwards search under terminal Vim and gVim work fine.

**Comment by Konfekt** [comment]
Dear @norbert-op , note that SumatraPDF has to be closed each time Vim is started anew.

**Comment by norbert-op** [comment]
I'm not getting the temp file error, so I'm not sure how to modify the setup. Can you figure that out on your end and pass the settings on to me? I agree that we have to figure that out before any further testing. `:VimtexView` simply has no response for me, without any error message.

As for the file names with spaces, the problem I'm seeing is empty buffers created during reverse search. Forward search with `cmd` works fine.

**Comment by Konfekt** [comment]
I cannot reproduce the problems for a file with spaces under 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 24 2019 01:24:41)
MS-Windows 64-bit GUI/console version with OLE support
Included patches: 1-2204
```
with neither `PowerShell 6.2.3`, nor 
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145
```
nor `cmd` under `Microsoft Windows [Versione 10.0.18362.449]`.

Note that your minimal `vimrc` differs slightly from that documented, in particular `%f` and `%l` are not escaped. For these settings, there occurs an error on inverse search such as
```
E492: Not an editor command: C:\Users\konfekt\test test.texl
```
Please try again with
```vim
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . ' -inverse-search "' . exepath(v:progpath) . ' --servername ' . v:servername
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
      \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

**Comment by Konfekt** [comment]
By the way, Vim starts alwayas as a server under MS Windows, therefore I removed the note in the documentation.

**Comment by Konfekt** [comment]
Perhaps also noteworthy is that under my system the path to `cmd` is `C:\WINDOWS\system32\cmd.exe` with the first folder name in capital letters. Therefore, `PowerShellOn()` is not called.

**Comment by lervag** [comment]
Ok, I'm still following this from a distance. Did I miss any questions or RFCs directed at me? Do you propose this is ready for merge, Konfekt?

**Comment by Konfekt** [comment]
Yes, I propose merging as it worked for me under all setups (minimal/normal vimrc, cmd, powershell, gvim, ...) as this improves the existing documentation. Then we work out with @norbert-op why it does not work out under his setup.

**Comment by lervag** [comment]
Thanks, I've merged now.

> Then we work out with @norbert-op why it does not work out under his setup.

Sounds good. Should we continue this here, or is it better to open a new issue and try to make it more clear exactly what is not working?

**Comment by norbert-op** [comment]
Thanks for the offer to work with my setup more. However, I don't have time to experiment with it further and I think I've reached the limit of my knowledge on this one. I can work fine without PowerShell in Vim, and if I do need it then I can toggle to it with my function.

**Comment by lervag** [comment]
Sounds good to me.

**Pull request closed without merging**
