### PR TITLE
Fixed #736: Works on Windows paths either with or without spaces.

### LINKED ISSUE #736: Continuous Compilation Hang (round 2)
I'm having a problem with vimtex on a Windows machine when spaces are in the path. The callback is not triggered successfully (so success/failure is never indicated). None of my settings in my vimrc file affect this. However, I have managed to correct for this problem by modifying `latexmk.vim`.  The change I made to [latexmk.vim](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/latexmk.vim#L816) is below.
```vim
call vimtex#util#set_default('g:vimtex_latexmk_progname',
      \ get(v:, 'progname', get(v:, 'progpath')))
```
"should" become
```vim
call vimtex#util#set_default('g:vimtex_latexmk_progname',
      \ get(v:, 'progpath', get(v:, 'progname')))
```
in order that the callback is able to message gvim. Note that, in my case, performing the above change modifies the default value of `g:vimtex_latexmk_progname` from `C:\Users\John Rinehart\Programs\vim_64\gvim.exe` to `gvim.exe` for me.

This seems related to #297.

### PR DESCRIPTION
**Pull request by fuzzybear3965**
Pushed to fix #736.

### CODE REVIEW

**Comment by lervag** [comment]
I'm looking forward to test this. I will:

1. Test to check if this works on my Windows machine,
2. Test if it breaks anything on Linux (obv. it shouldn't, but you never know),

If everything works, I'll tidy things up abit, then merge.

Thanks for your efforts so far, I really appreciate your help!

**Comment by fuzzybear3965** [comment]
No problem, @lervag. I'm happy to help. It takes a village, right? I'm happy to know that I can help (a bit) in making this more useful for people.

**Comment by haoyun** [comment]
I think #736 and #382 are the same problem. It was an old problem and was re-introduced in 4386c43.

**Comment by fuzzybear3965** [comment]
@haoyun, could you please try 9687a5a5b55b28c310f5b7d13302cffc940de50d?

**Comment by haoyun** [comment]
@fuzzybear3965 , I tested it just now. It solves the (at least my) problem!

**Comment by lervag** [comment]
I've not had the time to test this yet, sorry. I hope I will get time for that tomorrow evening, or at least by the weekend.

It is interesting that the problem was introduced again, because the commit that introduces it (30fb75b) was added after testing directly on windows. As stated before (at least to @fuzzybear3965), the current version works just fine for me on Windows 10.

Just a thought: Could the reason it works for me be because I have Git shell or similar applications installed?

In any case, I hope that it will turn out that the current PR will work also on my Windows test machine. If so, then I will merge this pretty soon.

**Comment by fuzzybear3965** [comment]
> I've not had the time to test this yet, sorry. I hope I will get time for that tomorrow evening, or at least by the weekend.

No problem.

> Just a thought: Could the reason it works for me be because I have Git shell or similar applications installed?

I don't think that would be the reason, although it *could* be. I don't think it is because:

  1. I'm pretty sure that the Git shell doesn't interface with `vimtex` at runtime, at all (`git` is used to set up `vader` for tests, but that's irrelevant to the `vimtex`'s use in practice).
  1. Related the first point, the command to compile the LaTeX document is done using the Windows command prompt which manages escaping (escaping being the seeming cause of these problems).
  1.  I have Git Bash (from Git for Windows) and the related `/usr/bin` binaries (`find`, `locate`, `grep`, `xargs', etc.) shipped with Git for Windows are on my PATH.

I say it *might* be because :

1. If I'm missing something and some UNIXey binaries (in the same family as those above) are used in the operation of the `perl` callback (implicitly, I mean, since I use Strawberry Perl) then I suppose that it *might* use one of the UNIXey binaries that are on my PATH from either the Windows Subsystem for Linux (which takes priority in a minority of cases, like `bash`) or from Git Bash (which takes priority in all cases where an equivalent binary isn't available through the `Windows Subsystem for Linux`. But, it seems that the issue is at the top level of escaping within the Windows command prompt. I imagine this could be confirmed by testing the `vimtex.comiler.cmd` within Windows command prompt where certain commands or certain flags could be replaced by random strings in order to confirm the issues lies within the Windows command prompt parsing. I imagine that this is the case, which would render this entire paragraph null and void.

**Comment by lervag** [comment]
Ok, I've finally tested. This does not work on my windows machine, so there is something strange going on here that we need to understand.

Some things that might be important:
- I'm using Vim 8.0.32 (installed usual way from vim.org)
- I'm testing by going to the `test/issues/736` folder in `cmd.exe`, then running `gvim -u minivimrc minimal.tex`
- I think I installed my latexmk through MikTeX, but I don't remember
- I have perl 5.22.0, I don't know/remember how I installed it (it may well be the Strawberry perl)
- I have latexmk 4.44

**Comment by lervag** [comment]
I'm wondering if it could be related to the `/s` in the `cmd` in `s:compiler_jobs.exec()`:

```vim
  let l:cmd = has('win32')
        \ ? 'cmd /s /c "' . self.cmd . '"'
        \ : ['sh', '-c', self.cmd]
```

Could you try to use the current master branch and remove the `/s` flag?

**Comment by fuzzybear3965** [comment]
I removed the `/s` flag from [here](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/compiler/latexmk.vim#L416). It didn't help. I've included the output of `:VimtexInfo` for the of both having had included the `/s` switch and having had removed it. Note that the command used to compile the document looks identical in both cases. The `/s` switch appears to have no effect.

#### `:VimtexInfo` output (switch removed)
```
vimtex project: minimal
  base: minimal.tex
  root: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736
  tex: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736\minimal.tex
  out:
  log:
  aux:
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIAFE46.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 10716 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -view=none -e "$success_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "minimal.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```

#### `:VimtexInfo` output (switch included)
```
vimtex project: minimal
  base: minimal.tex
  root: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736
  tex: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736\minimal.tex
  out:
  log:
  aux:
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIA83D4.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 7556 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -view=none -e "$success_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "minimal.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```

**Comment by lervag** [comment]
Ok, so, I'm simply totally confused. Why do things behave differently for me than for you?

Btw, I saw from one of the older posts that things worked for you with the extra number of double quotes. Does that still work, that is: `"""""" ... """"""` instead of `\" ... \"`? (Please also try with 4 instead of 6 sets of quotes.)

**Comment by fuzzybear3965** [comment]
> Ok, so, I'm simply totally confused. Why do things behave differently for me than for you?

I've thought a lot about this. I have no idea. Your guess is as good as mine. Of course, minor (and even major) version differences of `vim` and `perl` and `latexmk` are almost guaranteed not to cause any differences. The problem lies at the level of parsing a command on the command line. This should be consistent across any software configuration of a given OS. But, I have tested this on two different releases of 64-bit versions of Windows 10 (Pro and Education). So, I don't have inconsistency across OS versions/releases. But, you and I are reporting different results. We should really poll the audience to see what's most effective.

I include the `:VimtexInfo` output for the 4 quote and 6 quote cases. The 4 quote case failed. The 6 quote case succeeded (kind of). I still had to tweak the send expression. I include below, also, the changes I made to the current master branch. I note that with the test to be used for this issue, not only only does the PDF not appear upon successful completion (as mandated by the `minivimrc`) but also that calls to `:VimtexView` try to render the `.tex` document instead of the `.pdf` that's rendered (only in the 6 quote case). This problem exists with my commit, too. It doesn't happen in files where I use my own vimrc file, though. It seems to be a quirk associated with the `minivimrc`.

#### 6 quote code
```vim
        if has('win32')
          let l:cb = '""""""'
                \ . g:vimtex_compiler_progname
                \ . '""""""'
                \ . ' --servername ' . v:servername
        else
          let l:cb = vimtex#util#shellescape('"')
                \ . g:vimtex_compiler_progname
                \ . vimtex#util#shellescape('"')
                \ . ' --servername ' . v:servername
        endif

        " This seems more complicated than it is!
        " - The succes_cmd and fail_cmd are the same, except for the callback
        "   status value (1 and 0)
        " - We need to escape the parantheses on windows, but not on unix
        for [l:opt, l:val] in items({'success_cmd' : 1, 'failure_cmd' : 0})
          let l:func = l:cb . ' --remote-expr '
                \ . (has('win32')
                \   ? 'vimtex#compiler#callback(' . l:val . ')'
                \   : '\"vimtex\#compiler\#callback(' . l:val . ')\"')
          let l:cmd .= vimtex#compiler#latexmk#wrap_option(l:opt, l:func)
```

#### 4 quote `:VimtexInfo`
```
vimtex project: minimal
  base: minimal.tex
  root: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736
  tex: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736\minimal.tex
  out:
  log:
  aux:
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIA4BD2.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 9680 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -view=none -e "$success_cmd = '"""""gvim""""" --servername GVIM1 --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '"""""gvim""""" --servername GVIM1 --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "minimal.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```
and (six quotes)
```
vimtex project: minimal
  base: minimal.tex
  root: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736
  tex: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736\minimal.tex
  out: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736/minimal.pdf
  log: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736/minimal.log
  aux: C:\Users\John Rinehart\vimfiles\bundle\vimtex\test\issues\736/minimal.aux
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIAB1E.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 856 run
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -view=none -e "$success_cmd = '""""""gvim"""""" --servername GVIM1 --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""""gvim"""""" --servername GVIM1 --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "minimal.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```

**Comment by fuzzybear3965** [comment]
As a separate note, I just tested my code on a different file from the test/issue file we're working on, here. My commit doesn't work outside of the context of this `minivimrc` file. My commit does work for this test case, though (probably related to the `minivimrc` file).

That being said, I think the 6 quote code is superior to this commit. I can issue a separate PR or you can integrate the fix yourself. It doesn't matter to me.

**Comment by lervag** [comment]
I'll test myself with the 6 quote version. But I'm pretty sure that for me, the escaped `#` and `(` are needed.

I'm wondering if there could be any differences in our Vim settings (for some reason). Could you provide the output of `:set`, then I could diff it with my output.

Else I am just totally confused now. But since I don't use windows myself, I don't mind updating to the version that works for you. Let's first check the settings, though. And please do update the PR (just push a new commit to the same branch) with the 6 quote version.

**Comment by fuzzybear3965** [comment]
I'm not sure if you want `set` from my `vimrc` file or if you want `set` from the minivimrc file (probably the former, though). I give both below.

#### `set` (my `vimrc`)
```
--- Options ---
  autochdir           filetype=tex        number              syntax=tex
  autoindent          foldcolumn=4        ruler               tabstop=3
  background=dark     foldmethod=syntax   scroll=11           textwidth=80
  backupext=.bak      guioptions=         shiftwidth=3        timeoutlen=300
  commentstring=%%s   helplang=En         softtabstop=3       undofile
  display=lastline    hlsearch            spell               wildmenu
  encoding=utf-8      incsearch           spelllang=en_us
  expandtab           laststatus=2        splitbelow
  backspace=indent,eol,start
  comments=sO:% -,mO:%  ,eO:%%,:%
  define=\\\([egx]\|char\|mathchar\|count\|dimen\|muskip\|skip\|toks\)\=def\|\\font\|\\\(future\)\=let\|\\new\(count\|dimen\|skip\|muskip\|box\|toks\|read\|write\|fam\|insert\)\|\\\(re\)\=new\(boolean\|command\|counter\|environment\|font\|if\|length\|savebox\|theorem\(style\)\=\)\s*\*\=\s*{\=\|DeclareMathOperator\s*{\=\s*
  errorformat=%-P**%f,%-P**"%f",%E! LaTeX %trror: %m,%E%f:%l: %m,%E! %m,%Z<argument> %m,%Cl.%l %m,%+WLaTeX Font Warning: %.%#line %l%.%#,%-CLaTeX Font Warning: %m,%-C(Font)%m,%+WLaTeX %.%#Warning: %.%#line %l%.%#,%+WLaTeX %.%#Warning: %m,%+WOverfull %\%\hbox%.%# at lines %l--%*\d,%+WUnderfull %\%\hbox%.%# at lines %l--%*\d,%+WPackage natbib Warning: %m on input line %l%.,%+WPackage biblatex Warning: %m,%-C(biblatex)%.%#in t%.%#,%-C(biblatex)%.%#Please v%.%#,%-C(biblatex)%.%#LaTeX a%.%#,%-C(biblatex)%m,%-Z(babel)%.%#input line %l.,%-C(babel)%m,%+WPackage hyperref Warning: %m,%-C(hyperref)%.%#on input line %l.,%-C(hyperref)%m,%+WPackage scrreprt Warning: %m,%-C(scrreprt)%m,%+WPackage fixltx2e Warning: %m,%-C(fixltx2e)%m,%+WPackage titlesec Warning: %m,%-C(titlesec)%m,%-G%.%#
  fileencoding=utf-8
  fileencodings=ucs-bom,utf-8,default,latin1
  guifont=Consolas:h10:cANSI
  include=\v\\%(input|include)\{
  includeexpr=vimtex#include#expr()
  indentexpr=VimtexIndentExpr()
  indentkeys=0{,0},:,0#,!^F,o,O,e,[,(,{,),},],&,=item
  omnifunc=vimtex#complete#omnifunc
  runtimepath=~/vimfiles,~\vimfiles\bundle\Vundle.vim,~\vimfiles\bundle\vimtex,~\vimfiles\bundle\vim-snippets,~\vimfiles\bundle\vim-surround,~\vimfiles\bundle\mru,~\vimfiles\bundle\vim-go,~\vimfiles\bundle\nerdtree,~\vimfiles\bundle\emmet-vim,~\vimfiles\bundle\matchit,~\vimfiles\bundle\vim-airline,~\vimfiles\bundle\vim-airline-themes,~\vimfiles\bundle\vim-better-whitespace,~\vimfiles\bundle\nerdcommenter,~\vimfiles\bundle\julia-vim,~\vimfiles\bundle\vim-slime,~\vimfiles\bundle\vim-json,~\vimfiles\bundle\zoom.vim,~\vimfiles\bundle\csapprox,~\vimfiles\bundle\csv.vim,~\vimfiles\bundle\VimCompletesMe,~\vimfiles\bundle\rename.vim,~\vimfiles\bundle\vim-javascript,~\Programs\vim_64/vimfiles,~\Programs\vim_64,~\Programs\vim_64/vimfiles/after,~/vimfiles/after,~\vimfiles/bundle/Vundle.vim,~\vimfiles\bundle\Vundle.vim/after,~\vimfiles\bundle\vimtex/after,~\vimfiles\bundle\vim-snippets/after,~\vimfiles\bundle\vim-surround/after,~\vimfiles\bundle\mru/after,~\vimfiles\bundle\vim-go/after,~\vimfiles\bundle\nerdtree/after,~\vimfiles\bund
  statusline=%!airline#statusline(1)
  suffixes=.bak,~,.o,.h,.info,.swp,.obj,.sty,.cls,.log,.aux,.bbl,.out,.blg,.brf,.cb,.dvi,.fdb_latexmk,.fls,.idx,.ilg,.ind,.inx,.pdf,.synctex.gz,.toc
  suffixesadd=.tex,.sty,.cls
  termencoding=latin1
  undodir=~\vimfiles\undodir
  wildmode=longest,list,full
```

#### `set` (minivimrc)
```
--- Options ---
  autoindent          filetype=tex        syntax=tex
  commentstring=%%s   helplang=En
  comments=sO:% -,mO:%  ,eO:%%,:%
  define=\\\([egx]\|char\|mathchar\|count\|dimen\|muskip\|skip\|toks\)\=def\|\\font\|\\\(future\)\=let\|\\new\(count\|dimen\|skip\|muskip\|box\|toks\|read\|write\|fam\|insert\)\|\\\(re\)\=new\(boolean\|command\|counter\|environment\|font\|if\|length\|savebox\|theorem\(style\)\=\)\s*\*\=\s*{\=\|DeclareMathOperator\s*{\=\s*
  errorfile=~\vimfiles\bundle\vimtex\test\issues\736/minimal.log
  errorformat=%-P**%f,%-P**"%f",%E! LaTeX %trror: %m,%E%f:%l: %m,%E! %m,%Z<argument> %m,%Cl.%l %m,%+WLaTeX Font Warning: %.%#line %l%.%#,%-CLaTeX Font Warning: %m,%-C(Font)%m,%+WLaTeX %.%#Warning: %.%#line %l%.%#,%+WLaTeX %.%#Warning: %m,%+WOverfull %\%\hbox%.%# at lines %l--%*\d,%+WUnderfull %\%\hbox%.%# at lines %l--%*\d,%+WPackage natbib Warning: %m on input line %l%.,%+WPackage biblatex Warning: %m,%-C(biblatex)%.%#in t%.%#,%-C(biblatex)%.%#Please v%.%#,%-C(biblatex)%.%#LaTeX a%.%#,%-C(biblatex)%m,%-Z(babel)%.%#input line %l.,%-C(babel)%m,%+WPackage hyperref Warning: %m,%-C(hyperref)%.%#on input line %l.,%-C(hyperref)%m,%+WPackage scrreprt Warning: %m,%-C(scrreprt)%m,%+WPackage fixltx2e Warning: %m,%-C(fixltx2e)%m,%+WPackage titlesec Warning: %m,%-C(titlesec)%m,%-G%.%#
  include=\v\\%(input|include)\{
  includeexpr=vimtex#include#expr()
  indentexpr=VimtexIndentExpr()
  indentkeys=0{,0},:,0#,!^F,o,O,e,[,(,{,),},],&,=item
  omnifunc=vimtex#complete#omnifunc
  runtimepath=~/vimfiles/bundle/vimtex,~/vimfiles,~\Programs\vim_64/vimfiles,~\Programs\vim_64,~\Programs\vim_64/vimfiles/after,~/vimfiles/after,~/vimfiles/bundle/vimtex/after
  suffixes=.bak,~,.o,.h,.info,.swp,.obj,.sty,.cls,.log,.aux,.bbl,.out,.blg,.brf,.cb,.dvi,.fdb_latexmk,.fls,.idx,.ilg,.ind,.inx,.pdf,.synctex.gz,.toc
  suffixesadd=.tex,.sty,.cls
```

**Comment by lervag** [comment]
Preferably the latter, minivimrc.

Den søn. 23. apr. 2017, 19.56 skrev John Rinehart <notifications@github.com

**Comment by fuzzybear3965** [comment]
@lervag I screwed that up. Give me a minute and I'll clean up the commit history.

**Comment by lervag** [comment]
I'd prefer it if you did a rebase, in which case you move your own commits on top of the master branch. It seems that what you did now instead was to merge the master branch into your branch without any merge commits. A little bit strange, I think.

To fix, I would do the following:

1. Make a note of the relevant changes
2. With git shell or similar, do:

```sh
git co master
git reset --hard ORIGIN/master
```

3. Now apply the relevant changes and commit, then finally push your changes with `git push --force`.

Note: Here `ORIGIN` needs to be the right origin, i.e., the `lervag/vimtex` one. I think you should have two origins, see `git remote show -v`. You might need to add the origin as well, I don't know. Let me know if you need more help.

**Comment by lervag** [comment]
Regarding the `:set` output, there are some differences. I'm looking into them now. For one, I notice that when I use the `issues/736/minivimrc` (I hope this is the same one you're using) with `gvim -u minivimrc` (with Git Shell), I have 4 options that you don't:

```vim
set notextmode
set fileformat=unix
set scroll=14
set window=59
```

Also, I notice that my Vim is installed in `Program Files (x86)`, and yours is installed in `~\Programs\vim_64`. This is also interesting to me.

**Comment by lervag** [comment]
I don't see any reason that the `fileformat` should have anything to do with things, and `notextmode` is deprecated and should not do anything.

**Comment by fuzzybear3965** [comment]
I just double-checked. I'm using `issues/736` and I'm not sure why those options aren't appearing for me. I'm executing `gvim -u issues/736/minivimrc issues/736/minimal.tex`.

Oh, I think I know why those options aren't appearing. I'm using the [tuxproject.de builds of Vim.](https://tuxproject.de/projects/vim). Those might have different compiler options set. I download the self-extracting archive version (portable version) and install that to a folder filled with portable software.

**Comment by lervag** [comment]
Ok, perhaps I should try that version myself, just to check that it is not relevant. Or, if you have the time, you could try to install the normal version on vim.org and see if it makes any difference.

I'll probably have some more time for this tomorrow. And I think I'll merge this then, even though we have not understood the problem. And if the Vim version does not matter, which it probably doesn't, then I really have no idea what could cause this difference in behaviour. Thus I'm ready to let it be, since so far it seems I'm the only Windows user right now for which the current master branch works...?

**Comment by lervag** [comment]
And thanks, the commit history now looks good!

**Comment by fuzzybear3965** [comment]
> Ok, perhaps I should try that version myself, just to check that it is not relevant. Or, if you have the time, you could try to install the normal version on vim.org and see if it makes any difference.

No problem. I'll look into that tomorrow.

> And I think I'll merge this then, even though we have not understood the problem. 

Yeah, this really sucks. I'm hoping the vim.org installation will shed some light on the issue. The "why" (what's wrong) is really important for a good "what" (the solution).

**Comment by haoyun** [comment]
I tried both

1. ftp://ftp.vim.org/pub/vim/pc/gvim80-586.exe  (The official version that you mentioned)
2. https://github.com/vim/vim-win32-installer/releases (The one I previously used, I just need `+lua`, I think this is the same reason that @fuzzybear3965 uses  tuxproject.de version)

Neither works with `gvim -u minivimrc minimal.tex` in the folder `issues/736/`.

The `:set` output is the same as @fuzzybear3965 provided.

**Comment by fuzzybear3965** [comment]
@haoyun, thanks for the feedback. Are you saying that the 6 quote version (most recent commit) isn't working for you?

**Comment by haoyun** [comment]
Sorry. I didn't say it clearly.
The 6 quotes version works.

I was testing the `lervag:master` version  to see whether the problem was caused by different versions of VIM.

**Comment by fuzzybear3965** [comment]
Ah, thank you. Okay, @lervag, are you running your tests using a vim test framework (i.e. utilizing the command prompt indirectly) or are you running the command `gvim -u minivimrc minimal.tex` command from command prompt (like us)?

**Comment by lervag** [comment]
I'm running from command prompt (I have tried from both `cmd.exe` and `Git shell`).

Well, for now, I'll merge and clean up slightly. It doesn't matter to me that it won't work for me. I'll notify you if someone were to open an issue because it breaks for them on Windows, because then we have a "real" problem. :p

**Comment by lervag** [comment]
And thanks for testing the different Vim versions, @haoyun.

**Comment by lervag** [comment]
I've merged now. I also cleaned up and made sure it works on Linux as well. I changed it slightly, but I think it should still work as expected for you guys. The `shellescape` should turn two `"`s into 6. Let me know if it works.

**Pull request closed without merging**
