### PR TITLE
Add initial vader tests for qf/latexlog.vim

### PR DESCRIPTION
**Pull request by kiryph**
~~Could you squash the three commits to one (if you merge it)?
Honestly, I am struggling to sync my fork in such a way that you only see my most recent commit.
https://help.github.com/en/articles/syncing-a-fork does not help me. If you know a tutorial, how to
squash commits in a PR on the side of the one who has created the PR, I would happy to learn this.~~

This has been resolved. The new commits of this PR are actually meant to be individual commits.

### CODE REVIEW

**Comment by lervag** [comment]
Thanks!

My personal workflow would be something like this:

0. Development with more or less unstructured commits.

1. Rebase the commits with `git rebase -i master`. This makes it easy to e.g. squash or fixup commits.

2. After rebasing I sometimes need to do `git push --force` (or `git push -f` for short).

Force pushing may require people you cooperate with to do hard resets of their local versions of the branch. As long as your collaborators know how to do this or you are able to help, then this should be safe.

I'll look at the commit now.

**Comment by lervag** [comment]
Regardin the test: It looks pretty much great. However, some thoughts:

- If this should grow in proportion, then I think it could be nice just have the log file saved instead of generating it. I think it should/could be possible to load the file from a relative location, e.g. if we put it in `test/examples/quickfix` one could probably use `cfile ../examples/quickfix/main.log`. This would have another advantage in that one could include a `main.tex` file in the example directory, as well as a `minivimrc` file. This makes it useful also when debugging/developing towards this and related features.

- Each test should be relatively simple, so I would prefer to have several `Execute` lines that each do just one or a few things, instead of a single `Execute` that performs a lot of tests. Not really an issue now, though.

**Comment by kiryph** [comment]
Thanks for your help on git and your very welcome suggestions for the PR itself.

I could resolve my issue with git as following. My configuration of remotes was already correct (nothing to do, only verification):

```
❯ git remote -vv
origin	https://github.com/kiryph/vimtex.git (fetch)
origin	https://github.com/kiryph/vimtex.git (push)
upstream	https://github.com/lervag/vimtex.git (fetch)
upstream	https://github.com/lervag/vimtex.git (push)
```

In my case I had to throw away a few "new" commits (changed commiter compared to upstream) with 

`❯ git reset --hard HEAD~3`

The most important step was a rebase with upstream master with no "new" commits on the branch:

`❯ git rebase upstream/master`

And then commit my changes: here add two new files

```
❯ git add -f logparser.vader
❯ git add -f ../examples/quickfix/main.log
```

And finally as you said

```
❯ git push --force origin master
```
---

Regarding you second suggestion:
Does this necessarily mean we have to `setf tex` for each test and hence `vimtex#init()` is run several times?
I would assume writing the test in this way increases the runtime of the test. Is this correct?

**Comment by lervag** [comment]
> Does this necessarily mean we have to setf tex for each test and hence vimtex#init() is run several times?
I would assume writing the test in this way increases the runtime of the test. Is this correct?

I think you can let the first `Execute` setup things for the following tests. I.e., something like this:

```
Execute (Setup):
  setfiletype tex
  cfile ../examples/quickfix/main.log

Execute (Verify captured LaTeX logfile warnings: total number):
  Log len(getqflist())
  AssertEqual 2, len(getqflist())

Execute (Verify captured LaTeX logfile warnings: package natbib):
  AssertEqual 'Package natbib Warning: Citation `Einstein:1905'' on page 1 undefined on input line 99.', getqflist()[0]['text']
  AssertEqual 99, getqflist()[0]['lnum']
  AssertEqual 'W', getqflist()[0]['type']

Execute (Verify captured LaTeX logfile warnings: package refcheck (general pattern)):
  AssertEqual 'Package refcheck Warning: Unused label `eq:my_equation_label'' on input line 12.', getqflist()[1]['text']
  AssertEqual 12, getqflist()[1]['lnum']
  AssertEqual 'W', getqflist()[1]['type']
```

Note the first `Execute` now simply sets up the buffer, whereas the following ones applies the assertions. However, I would expect that we might need a cleanup for this to work well when we perform the entire test suite.

**Comment by lervag** [comment]
I just tested very briefly, and it seems my suggestion works as expected and that there is no need for cleanup. I.e., simply use the initial `Execute` block for setup, then subsequent blocks for applying the tests.

**Comment by lervag** [comment]
> I would assume writing the test in this way increases the runtime of the test. Is this correct?

My suggestion should not increase runtime very much, since we only prepare the test buffer once. If we used the `Before` block, then it would be executed everytime, but that is not needed here.

**Comment by kiryph** [comment]
Yes, this is faster and scales much better when adding more tests.

**Comment by kiryph** [comment]
By the way for a `git commit --amend`, I had to change slightly the commit message so that the new commit actually shows up here.
Maybe it is better when I create a new commit, then rebase and finally do a forced push so that we have single commit here.

**Comment by lervag** [comment]
> By the way for a git commit --amend and git push --force, I had to change slightly the commit message so that the new commit actually shows up here.
Maybe it is better when I create a new commit, then rebase and finally do a forced push so that we have single commit here.

I am not quite sure what you mean. If you ammend a commit and force push, then the PR should be updated as expected. In any case, I don't mind multiple commits. I prefer commits to be made "logically", and as such I encourage that one uses rebase and friends to make things more clear. But I also don't mind very much if people write PRs with several chronological commits. In such cases I might squash before merging. My main concern is that the diff between the master and PR looks good.

**Comment by lervag** [comment]
Btw, let me know when it is time for me to consider your PR for merging.

**Comment by kiryph** [comment]
>  If you ammend a commit and force push, then the PR should be updated as expected.

It did not work with my first force push:

> kiryph force-pushed the kiryph:vader-latexlog  branch from 5897d83 to d87ab53 an hour ago

Anyhow, I will watch this in the future. Maybe I checked too quickly and github had not updated yet.

---

> Btw, let me know when it is time for me to consider your PR for merging.

If you want, you can merge. Following could become a new issue or pr. I think you prefer when issues/prs address only one thing.

In the next step I wanted to point out that the multi-line messages of hyperref

```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\gamma' on input line 9.

Package hyperref Warning: Composite letter `\textdotbelow+u'
(hyperref)                not defined in PD1 encoding,
(hyperref)                removing `\textdotbelow' on input line 5.
```

are currently captured incompletely. 

The messages in the quickfix window are cut off

```
|9 warning| Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
|5 warning| Package hyperref Warning: Composite letter `\textdotbelow+u' not defined in PD1 encoding,
```

Following change would improve this

```diff
   if get(self.config.packages, 'hyperref', l:default)
     setlocal errorformat+=%+WPackage\ hyperref\ Warning:\ %m
-    setlocal errorformat+=%-C(hyperref)%.%#on\ input\ line\ %l.
+    setlocal errorformat+=%-C(hyperref)%m\ on\ input\ line\ %l.
   endif
```

```
|9 warning| Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding): removing `\gamma'
|5 warning| Package hyperref Warning: Composite letter `\textdotbelow+u' not defined in PD1 encoding, removing `\textdotbelow'
```

However, I was struggling to write the test. The messages in `getqflist()[2]['text']` and `getqflist()[3]['text']`  contain non-visible whitespace which I failed to transfer correctly into `logparser.vader`.
I was using `Ctrl-r = getqflist()[2]['text']`.

Steps to reproduce

1. add both messages to main.log
```
❯ cat main.log
Package natbib Warning: Citation `Einstein:1905' on page 1 undefined on input line 99.
Package refcheck Warning: Unused label `eq:my_equation_label' on input line 12.
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\gamma' on input line 9.
Package hyperref Warning: Composite letter `\textdotbelow+u'
(hyperref)                not defined in PD1 encoding,
(hyperref)                removing `\textdotbelow' on input line 5.
```

2. Run manually :cfile
```
$ vim
:setf tex
:cfile main.log 
:copen
```

3. Edit `logparser.vader`

duplicate `Execute block` and adapt for new messages with Ctrl-r=getqflist()[2]['text']

```
Execute (Verify captured LaTeX logfile warnings: package hyperref):
  AssertEqual 'Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
                removing `\gamma'', getqflist()[2]['text']
  AssertEqual 12, getqflist()[2]['lnum']
  AssertEqual 'W', getqflist()[2]['type']
```
Do you know how to format this?

**Comment by kiryph** [comment]
I have resolved my issue which I mentioned in my previous comment.

For now, I am finished with the fixes for parsing the log file and writing tests.

If you have further ideas, I am happy to incoporate them.

**Comment by lervag** [comment]
Great! This is a valuable contribution, both wrt. the update to the latexlog parsing, but perhaps especially due to the added tests! Thanks!

**Pull request merged**
