### PR TITLE
Allow creating starred command

### PR DESCRIPTION
**Pull request by Aster89**
I know that `tsc` exists, but would this change be out of the world?

### CODE REVIEW

**Comment by lervag** [comment]
No, this does not seem bad. Perhaps you could include a test for this, e.g. in [this file](https://github.com/Aster89/vimtex/blob/master/test/test-commands/test-insert-cmd.vim)?

**Comment by Aster89** [comment]
At the moment if I run ` MYVIM="vim -T dumb --not-a-term --noplugin -n" make` in a clean repo, it fails. Can't even tell how, as the terminal gets rewritten so I'm not sure what come first and what last. I see this (it's a video):
[asciicast](https://asciinema.org/a/j0ugyWQKpS9AIpinegNCrAfpU)


Besides, I guess we also want that hitting <kbd>F7</kbd> when the cursor is at `|` in insert mode in `foo*|bar` causes the result to be `\foo*{bar|`, right? If so, my change doesn't work this way yet. I have to improve it :D

**Comment by Aster89** [comment]
> Besides, I guess we also want that hitting F7 when the cursor is at `|` in insert mode in `foo*|bar` causes the result to be `\foo*{bar|`, right? If so, my change doesn't work this way yet. I have to improve it :D

Done because why not, but I couldn't run the tests.

**Comment by lervag** [comment]
Thanks! I fixed the failing tests before merging.

**Pull request merged**
