### PR TITLE
Improve subfiles handling (addresses #1702)

### PR DESCRIPTION
**Pull request by lervag**
Currently a work in progress, requires ~~more robust code~~ and persistent tests. But it seems to fix the issue raised in #1702.

### CODE REVIEW

**Comment by thor** [comment]
I've tested the changes with regards to the table of contents alone, and it seems to work very well! :+1: If I understand correctly, you've added/altered the `\subfile` variants to be treated in the same way as the `\import`, and then get their location and use that to parse the files relative to the file they're included from(?).

I'm not sure what the other issue at hand is... I think. 
I thought I was able to compile the `parts/chapter.tex` in standalone mode, but I can't seem to, not via vimtex or with `latexmk` directly from within the root folder. I'm a bit confused where my thoughts were or what I did in addition, so I'll have to fiddle around with that again. I thought I could, but I can't, thus I must've misunderstood something essential.

**Comment by lervag** [comment]
> I've tested the changes with regards to the table of contents alone, and it seems to work very well!

Great, happy to hear it!

> If I understand correctly, you've added/altered the \subfile variants to be treated in the same way as the \import, and then get their location and use that to parse the files relative to the file they're included from(?).

Yes, exactly. There are two main changes: One for the TeX parser to allow `\subfile{path}` to be relative to the current file, and a second to do the same for the table-of-contents parser.

> I thought I was able to compile the parts/chapter.tex in standalone mode, but I can't seem to, not via vimtex or with latexmk directly from within the root folder. I'm a bit confused where my thoughts were or what I did in addition, so I'll have to fiddle around with that again. I thought I could, but I can't, thus I must've misunderstood something essential.

Ah, yes. I never considered you might have made a wrong basic assumption. I think the problem is that we need a consistent root path. When we run `latexmk` from the `main.tex` directory, then `sections/first.tex` is not properly rooted. If we were to run `latexmk` from the `chapter.tex` directory, then the `main.tex` in `\documentclass[main.tex]{subfiles}` is not properly rooted. I think the conclusion is that all the `\subfile` commands should have either absolute paths or paths relative to the `main.tex` file.

Note that the `import` package works differently here, in that it "changes the CWD" to the imported package. This is quite well explained in the [short, two page manual](http://texdoc.net/texmf-dist/doc/latex/import/import.pdf).

I've looked into the [`subfiles` manual](http://texdoc.net/texmf-dist/doc/latex/subfiles/subfiles.pdf) as well, which seems to claim that this exact workflow _should_ work. However, it seems my above paragraph is still correct. That is, you would have to use `\documentclass[../main.tex]{subfiles}` in `chapter.tex` to make things compile correctly. So, I think an appropriate change is something like this:

1. Update the docs to explain this behaviour.

    ```
    It is important to note that the main-file path in
    `\documentclass[path]{subfiles}` implicitly indicates which root directory
    should be used for compilation. This is important, because the root
    directory in turn specifies the parent path for nested imports, includes,
    subfiles, includegraphics, and similar. See Section 3.1 in the manual of
    subfiles [1] for an example of a project with nested root directories.

    Vimtex will automatically try to parse the root path from the
    `\documentclass` macro to be consistent with this behaviour of the subfiles
    package.
    ```

2. Update the code to properly specify the root path for the subfile mode.

What do you think?

**Comment by thor** [comment]
>  I think the conclusion is that all the `\subfile` commands should have either absolute paths or paths relative to the main.tex file.

To clarify that I do not misunderstand: that's absolute paths being relative paths seen from `main.tex` vs. relative paths being the path to `main.tex` as seen from each individual `*.tex` file.

---

Provided I have not miserably failed at my working example --- I'm not sure it is possible to only use absolute paths for multi-level hierarchies, although I would much prefer it.

In an attempt to create a setup where I can execute `latexmk` from `main.tex` and the target can be any of the documents, I am not able to get more than one of the two: I can't find a way where I can compile `parts/chapter.tex` and `main.tex` using `latexmk` from the root directory.

If I use absolute paths then 



> > I thought I was able to compile the parts/chapter.tex in standalone mode, but I can't seem to, not via vimtex or with latexmk directly from within the root folder. I'm a bit confused where my thoughts were or what I did in addition, so I'll have to fiddle around with that again. I thought I could, but I can't, thus I must've misunderstood something essential.
> 
> Ah, yes. I never considered you might have made a wrong basic assumption. I think the problem is that we need a consistent root path. When we run `latexmk` from the `main.tex` directory, then `sections/first.tex` is not properly rooted. If we were to run `latexmk` from the `chapter.tex` directory, then the `main.tex` in `\documentclass[main.tex]{subfiles}` is not properly rooted. I think the conclusion is that all the `\subfile` commands should have either absolute paths or paths relative to the `main.tex` file.

Right, indeed. If the current working directory remains the root folder, then one would assume all paths should be relative to the current working directory. However, I'm not sure that is the case.

> Note that the `import` package works differently here, in that it "changes the CWD" to the imported package. This is quite well explained in the [short, two page manual](http://texdoc.net/texmf-dist/doc/latex/import/import.pdf).
> 
> I've looked into the [`subfiles` manual](http://texdoc.net/texmf-dist/doc/latex/subfiles/subfiles.pdf) as well, which seems to claim that this exact workflow _should_ work. However, it seems my above paragraph is still correct. That is, you would have to use `\documentclass[../main.tex]{subfiles}` in `chapter.tex` to make things compile correctly. So, I think an appropriate change is something like this:

From the `subfiles` documentation it is mentioned that `\subfile{}` itself uses `import`. I interpret that to mean that any use of `\subfile{}` will be rooted in the directory of the file including it. Assuming that is the case the only documents that can use a path relative to `main.tex` are those in the same folder as `main.tex`, whereas all others must use a path relative to their own location.

A somewhat messy execution table highlighting how this works for the example files in #1702:

| CWD      | Root `parts/chapter.tex` | Subfiles `parts/chapter.tex` | `latexmk chapter.tex>` | `latexmk main.tex` |
|----------|--------------------------|------------------------------|:----------------------:|:------------------:|
| `/`      | `main.tex`               | `sections/*.tex`             | ❌                     | ✅                 |
| `/`      | `main.tex`               | `parts/sections/*.tex`       | ✅                     | ❌                 |
| `/`      | `../main.tex`            | `sections/*.tex`             | ❌                     | ✅                 |
| `/`      | `../main.tex`            | `parts/sections/*.tex`       | ✅                       | ❌                 |
| `/parts` | `main.tex`               | `sections/*.tex`             | ❌                     | ❌                 |
| `/parts` | `main.tex`               | `parts/sections/*.tex`       | ❌                     | ❌                 |
| `/parts` | `../main.tex`            | `sections/*.tex`             | ✅                     | ❌                 |
| `/parts` | `../main.tex`            | `parts/sections/*.tex`       | ❌                     | ❌                 |

To me this seems to suggest that the only approach is to execute `latexmk` in the folder of the current file (if `main parser` is *local file* and not `subfiles`, as a result of switching target). However, I feel as though I'm missing something. I thought it would be possible to use absolute paths as you mentioned, but since `subfiles` uses `import` and case no. 2 only works for `chapter.tex`, it seems like that cannot be the case? :shrug: 

> 1. Update the docs to explain this behaviour.
>    ```
>    It is important to note that the main-file path in
>    `\documentclass[path]{subfiles}` implicitly indicates which root directory
>    should be used for compilation. This is important, because the root
>    directory in turn specifies the parent path for nested imports, includes,
>    subfiles, includegraphics, and similar. See Section 3.1 in the manual of
>    subfiles [1] for an example of a project with nested root directories.
>    
>    Vimtex will automatically try to parse the root path from the
>    `\documentclass` macro to be consistent with this behaviour of the subfiles
>    package.
>    ```
> 2. Update the code to properly specify the root path for the subfile mode.
> 
> What do you think?

Per above, making the optimistic and simultaneously pessimistic assumption that I haven't messed up in the testing, I think *"This is important, because the root directory in turn specifies the parent path for nested imports, includes, subfiles, includegraphics, and similar."* might not be correct --- at least for `\import{}` and `\subfiles{}`, perhaps not for `\includegraphics{}` either per `subfile2.tex` in the `subfiles` documentation sec. 3.1.

**Comment by lervag** [comment]
Thanks for the thorough post. I've tried to respond in depth. I hope you might find time to test my below table of commands and verify (or falsify) my expectations.

> To clarify that I do not misunderstand: that's absolute paths being relative paths seen from `main.tex` vs. relative paths being the path to `main.tex` as seen from each individual `*.tex` file.

No, with absolute path I mean paths like `/home/user/path/main.tex`, i.e. paths that begin with `/`. Relative paths are paths that are not absolute, e.g. `../main.tex`. This latter form requires a well defined starting point.

----

So, to be pragmatic: we need to figure out how to handle things within vimtex. A couple of thoughts related to your comments first.

> Right, indeed. If the current working directory remains the root folder, then one would assume all paths should be relative to the current working directory. However, I'm not sure that is the case.

Yes, this was what I tried to say in my previous comment. Still, ...

> From the `subfiles` documentation it is mentioned that `\subfile{}` itself uses `import`. I interpret that to mean that any use of `\subfile{}` will be rooted in the directory of the file including it. Assuming that is the case the only documents that can use a path relative to `main.tex` are those in the same folder as `main.tex`, whereas all others must use a path relative to their own location.

I agree, from the `subfiles` docs it would seem like one should have a similar behaviour. However, as you show quite clearly, this is not the case. `subfiles` seems to be strongly connected to the original working directory. Some remarks:

* In your tests, with `CWD` set to `/`, did you use `latexmk parts/chapter.tex`? And similar, with `CWD` set to `/parts`, did you run `latexmk ../main.tex`? In general, I think the latter variant would not work.

* Based on my previous comment, I would propose the following table of tests:

    | CWD      | Root          | Subfiles               | Command 1             | Command 2                   |
    | ---      | ---           | ---                    | ---                   | ---                         |
    | `/`      | `main.tex`    | `sections/*.tex`       | `latexmk main.tex`    | `latexmk parts/chapter.tex` |
    | `/`      | `main.tex`    | `parts/sections/*.tex` | `latexmk main.tex`    | `latexmk parts/chapter.tex` |
    | `/parts` | `main.tex`    | `sections/*.tex`       | `latexmk ../main.tex` | `latexmk chapter.tex`       |
    | `/parts` | `main.tex`    | `parts/sections/*.tex` | `latexmk ../main.tex` | `latexmk chapter.tex`       |
    | `/parts` | `../main.tex` | `sections/*.tex`       | `latexmk ../main.tex` | `latexmk chapter.tex`       |
    | `/parts` | `../main.tex` | `parts/sections/*.tex` | `latexmk ../main.tex` | `latexmk chapter.tex`       |

  Here I would expect the commands in rows 2 and 5 to both succeed, and all other commands to fail.

> Per above, making the optimistic and simultaneously pessimistic assumption that I haven't messed up in the testing, I think _"This is important, because the root directory in turn specifies the parent path for nested imports, includes, subfiles, includegraphics, and similar."_ might not be correct --- at least for `\import{}` and `\subfiles{}`, perhaps not for `\includegraphics{}` either per `subfile2.tex` in the `subfiles` documentation sec. 3.1.

I don't quite see why my description is wrong. That is, if my above table of suggested commands with my expactations of the outcome is correct, then I think it confirms my text. Except for `\import{}`, which I think you are right about. As we've already discussed, `\import` does change the CWD (it is the entire point of the package and command).

**Comment by thor** [comment]
> Thanks for the thorough post. I've tried to respond in depth. I hope you might find time to test my below table of commands and verify (or falsify) my expectations.

No worries, it's the least I can as someone who opened an issue on your issue tracker. Both for the previous post and this one I'd like to apologise for the occasional misunderstanding due to excessive brewity or incorrect assumptions. I think it's pretty clear I've got some terminology mixed up.

> > To clarify that I do not misunderstand: that's absolute paths being relative paths seen from `main.tex` vs. relative paths being the path to `main.tex` as seen from each individual `*.tex` file.
> 
> No, with absolute path I mean paths like `/home/user/path/main.tex`, i.e. paths that begin with `/`. Relative paths are paths that are not absolute, e.g. `../main.tex`. This latter form requires a well defined starting point.

That's my usual understanding of absolute vs relative paths too. In the case of the issue #155 it seemed to be used to distinguish between paths relative to themselves and paths relative to the root document. To be clear on my own use, any further use of root path on my end refers to relative paths from the location/working directory of the *main document*.

>So, to be pragmatic: we need to figure out how to handle things within vimtex. A couple of thoughts related to your comments first.
>
>> Right, indeed. If the current working directory remains the root folder, then one would assume all paths should be relative to the current working directory. However, I'm not sure that is the case.
>
>Yes, this was what I tried to say in my previous comment. Still, ...

Ah, my apologies for not catching that.

>
>> From the `subfiles` documentation it is mentioned that `\\subfile{}` itself uses `import`. I interpret that to mean that any use of `\\subfile{}` will be rooted in the directory of the file including it. Assuming that is the case the only documents that can use a path relative to `main.tex` are those in the same folder as `main.tex`, whereas all others must use a path relative to their own location.
>
>I agree, from the `subfiles` docs it would seem like one should have a similar behaviour. However, as you show quite clearly, this is not the case. `subfiles` seems to be strongly connected to the original working directory. Some remarks:

A quick reply here: I think it may be connected (primarily) to the original working directory for the primary compilation target, but not equally so for the included subfiles, as ...

>* In your tests, with `CWD` set to `/`, did you use `latexmk parts/chapter.tex`? And similar, with `CWD` set to `/parts`, did you run `latexmk ../main.tex`? In general, I think the latter variant would not work.
>
>* Based on my previous comment, I would propose the following table of tests:
>
> ... [snip] ...

I'm not sure if it does show that it is not the case. Firstly, to clear up the table in the previous post. The invocations of `latex main.tex` and `latex chapter.tex` were with their relative paths, thus `latex ../main.tex` when `cwd` was `/parts`, and `latex parts/chapter.tex` when `cwd` was `/`.
As such I believe the table in the previous post covers all of the six invocations requested.
(I agree that `latex ../main.tex` from within `parts` was expected to fail, but I thought I might as well included it for the sake of the structure in the table, heh.)

The ❌ specifically meant that compilation failed either due to not finding `main.tex` from the `subfiles` document class parameter or `first.tex`. The latter was the primary cause.

>Here I would expect the commands in rows 2 and 5 to both succeed, and all other commands to fail.

As far as I am able to reproduce it correctly they do not succeed (for both command 1 and 2).

| CWD      | `chapter.tex` root          | Subfiles               | Command 1             | Command 2                   | C1 | C2 |
| ---      | ---           | ---                    | ---                   | ---                         |:--:|:--:|
| `/`      | `main.tex`    | `parts/sections/*.tex` | `latexmk main.tex`    | `latexmk parts/chapter.tex` | ❌ | ✔ |

This is the invocation from row 2: building `parts/chapter.tex` succeeds, but `main.tex` does not.

The only way I can rationalise that (absent other things interferring) is that the inclusion of `parts/chapter.tex` from `main.tex` results in `cwd` being changed to `/parts` when `\subfile` is used within `parts/chapter.tex`, thus unable to find `parts/sections/*.tex` from its location. However, quite why that does not happen when `parts/chapter.tex` is built directly is something I can't quite explain. Does `import` possibly work differently depending on whether it's building a subfile independently or whether it is being included? That *seems* sensible to me, but I'm not sure. (A worthwhile idea here would be to replace the `\subfile` invocations in `parts/chapter.tex` to see if it is `import` specific or `subfile` specific.)

| CWD      | `chapter.tex` root          | Subfiles               | Command 1             | Command 2                   | C1 | C2 |
| ---      | ---           | ---                    | ---                   | ---                         |:--:|:--:|
| `/parts` | `../main.tex` | `sections/*.tex`       | `latexmk ../main.tex` | `latexmk chapter.tex`       | ❌ | ✔ |

This in the invocation from row 7: building `chapter.tex` succeeds, but `main.tex` does not (as expected).

(In the event row 2 and 5 included the header row then, sans header row, row 1 and row 6 are those invocations, where for the first case only `latex main.tex` works, and neither works for the second.)

>> Per above, making the optimistic and simultaneously pessimistic assumption that I haven't messed up in the testing, I think _"This is important, because the root directory in turn specifies the parent path for nested imports, includes, subfiles, includegraphics, and similar."_ might not be correct --- at least for `\import{}` and `\subfiles{}`, perhaps not for `\includegraphics{}` either per `subfile2.tex` in the `subfiles` documentation sec. 3.1.
>
>I don't quite see why my description is wrong. That is, if my above table of suggested commands with my expactations of the outcome is correct, then I think it confirms my text. Except for `\import{}`, which I think you are right about. As we've already discussed, `\import` does change the CWD (it is the entire point of the package and command).

I find it somewhat strange myself, but if you'd like I'll whip up a repository for attempting to reproduce it with the various variants if you'd like? Might uncover what's causing the different experience.

**Comment by lervag** [comment]
> No worries, it's the least I can as someone who opened an issue on your issue tracker. Both for the previous post and this one I'd like to apologise for the occasional misunderstanding due to excessive brewity or incorrect assumptions. I think it's pretty clear I've got some terminology mixed up.

No problem, I mix up things all the time :)

> That's my usual understanding of absolute vs relative paths too. In the case of the issue #155 it seemed to be used to distinguish between paths relative to themselves and paths relative to the root document. To be clear on my own use, any further use of root path on my end refers to relative paths from the location/working directory of the _main document_.

Ok.

> > > From the `subfiles` documentation it is mentioned that `\\subfile{}` itself uses `import`. I interpret that to mean that any use of `\\subfile{}` will be rooted in the directory of the file including it. Assuming that is the case the only documents that can use a path relative to `main.tex` are those in the same folder as `main.tex`, whereas all others must use a path relative to their own location.
> > 
> > 
> > I agree, from the `subfiles` docs it would seem like one should have a similar behaviour. However, as you show quite clearly, this is not the case. `subfiles` seems to be strongly connected to the original working directory. Some remarks:
> 
> A quick reply here: I think it may be connected (primarily) to the original working directory for the primary compilation target, but not equally so for the included subfiles, as ...

Ah, yes. I think I see now. It is not so hard, and it is exactly as stated in the docs: `\subfile` works exactly the same as specified in the `import` package. Each `\subfile` command will change the CWD for the subfile, and so the main path must be relative to the subfile. The example on page 3 in [the docs for `subfiles`](https://ctan.uib.no/macros/latex/contrib/subfiles/subfiles.pdf) is actually quite clear.

This is the effect on your example:

* `main.tex` says `\subfile{parts/chapter.tex}`, this implies that within `chapter.tex` the CWD for further `\include` type commands will be `parts/`. Thus, the subsequent `\subfile{sections/first.tex}` works as expected when we compile `main.tex`.
* However, this also means that we need to compile `chapter.tex` from `parts/`. Thus, for things to work consistently, it is also necessary to specify the `main.tex` path relative to the current subfile. That is, we need `\documentclass[../main.tex]{subfiles}` in `chapter.tex`.

The following update to the docs should then make things correct and consistent with the subfiles documentation, I think:

```
  Absolute paths to the main file (e.g. `/home/user/main.tex`) will work as
  expected. Relative paths must be relative to the current subfile. So, for
  a project structured like this:

    main.tex
    sub/sub.tex

  We need `\documentclass[../main.tex]{subfiles}` in `sub.tex`.
```

Note: This also requires an update of vimtex. Before I look into the code, it would be good to hear if you agree with me.

**Comment by thor** [comment]
> > > > From the `subfiles` documentation it is mentioned that `\\subfile{}` itself uses `import`. I interpret that to mean that any use of `\\subfile{}` will be rooted in the directory of the file including it. Assuming that is the case the only documents that can use a path relative to `main.tex` are those in the same folder as `main.tex`, whereas all others must use a path relative to their own location.
> > > 
> > > 
> > > I agree, from the `subfiles` docs it would seem like one should have a similar behaviour. However, as you show quite clearly, this is not the case. `subfiles` seems to be strongly connected to the original working directory. Some remarks:
> > 
> > 
> > A quick reply here: I think it may be connected (primarily) to the original working directory for the primary compilation target, but not equally so for the included subfiles, as ...
> 
> Ah, yes. I think I see now. It is not so hard, and it is exactly as stated in the docs: `\subfile` works exactly the same as specified in the `import` package. Each `\subfile` command will change the CWD for the subfile, and so the main path must be relative to the subfile. The example on page 3 in [the docs for `subfiles`](https://ctan.uib.no/macros/latex/contrib/subfiles/subfiles.pdf) is quite clear.
Right! Every invocation of `\subfile{}` changes it; the contents of the document class naturally does not matter to the inclusion of the file itself.

> This is the effect on your example:
> 
>     * `main.tex` says `\subfile{parts/chapter.tex}`, this implies that within `chapter.tex` the CWD for further `\include` type commands will be `parts/`. Thus, the subsequent `\subfile{sections/first.tex}` works as expected when we compile `main.tex`.
> 
>     * However, this also means that we need to compile `chapter.tex` from `parts/`. Thus, for things to work consistently, it is also necessary to specify the `main.tex` path relative to the current subfile. That is, we need `\documentclass[../main.tex]{subfiles}` in `chapter.tex`.

Indeed, that seems to fit rather well with my earlier experience of trying to compile both documents.
(A note is that is also how the LaTeX Workshop extension for VSCode seems to do it.)

> The following update to the docs should then make things correct and consistent with the subfiles documentation, I think:
> 
> ```
>   Absolute paths to the main file (e.g. `/home/user/main.tex`) will work as
>   expected. Relative paths must be relative to the current subfile. So, for
>   a project structured like this:
> 
>     main.tex
>     sub/sub.tex
> 
>   We need `\documentclass[../main.tex]{subfiles}` in `sub.tex`.
> ```
> 
> Note: This also requires an update of vimtex. Before I look into the code, it would be good to hear if you agree with me.

I agree. FWIW I think there might be some curious or minor frustrations when compiling from different working directions. For instance, how to deal with `latexmkrc` in the root folder? Then there's `build_dir` for the `vimtex_compiler_latexmk`; should it always be presumed to be relative to the root location? While I think the latter question is easy, I imagine there might be other issues or things that might jam the gears a bit for a "simple" or entirely non-invasive change?

All the better if that's not the case though. :)

**Comment by lervag** [comment]
> I agree. FWIW I think there might be some curious or minor frustrations when compiling from different working directions. For instance, how to deal with latexmkrc in the root folder? Then there's build_dir for the vimtex_compiler_latexmk; should it always be presumed to be relative to the root location? While I think the latter question is easy, I imagine there might be other issues or things that might jam the gears a bit for a "simple" or entirely non-invasive change?

Yes, definitely. I agree. However, I think we should take things one step at a time. That is: I'll now fix the code and make things work as I've proposed. I think that should make things consistent with the `subfiles` and `import` packages.

Then, afterwards, you or others can open new issues to raise these minor frustrations that follow. Some of them may be difficult to handle (e.g. dealing with `latexmkrc` in the root folder), but others might be possible to find solutions for.

**Comment by thor** [comment]
That sounds good. A quick follow-up is that after playing around with https://github.com/James-Yu/LaTeX-Workshop I wonder _not_ changing the directory is the ideal approach for the `latexmk` engine specifically. I'm not sure if perhaps we should move this to a dedicated issue as this might not be quite the place, but in the spirit of brewity: `latexmk` has a `-cd`/`$do_cd` alternative that kind of solves parts of the issue.

It's quite neat, but creates a kind of dependency on `latexmk`.It changes the directory when building the file, so you do not have to fiddle or struggle with getting the `latexmkrc` loaded depending on where you are in the tree.

**Comment by lervag** [comment]
> That sounds good.

Great, I'll update the PR when I get the time.

> A quick follow-up is that after playing around with https://github.com/James-Yu/LaTeX-Workshop I wonder _not_ changing the directory is the ideal approach for the `latexmk` engine specifically. I'm not sure if perhaps we should move this to a dedicated issue as this might not be quite the place, but in the spirit of brewity: `latexmk` has a `-cd`/`$do_cd` alternative that kind of solves parts of the issue.

> It's quite neat, but creates a kind of dependency on `latexmk`.It changes the directory when building the file, so you do not have to fiddle or struggle with getting the `latexmkrc` loaded depending on where you are in the tree.

That could be neat, but I'm not quite sure. In any case, I think it best to first make things work in general, then we can look into improvements at the next stage. So, feel free to open a new issue after this PR is finished and merged, and we can continue the discussion then. Sounds good?

**Comment by thor** [comment]
Sounds good! I'll follow-up with an attempt at adequately described issues.
:)

**Comment by lervag** [comment]
I think the newly updated (force pushed) branch should work according to the updated docs. I would be happy if you could test if I've missed anything, then I'll merge to master if things work as expected now.

> Sounds good! I'll follow-up with an attempt at adequately described issues.

Great. And no worries :)

**Comment by thor** [comment]
While it, unfortunately, breaks my current workflow by changing the directory it seems to otherwise work just as expected! :+1:

**Comment by lervag** [comment]
Good. Then I'll merge shortly.

**Comment by lervag** [comment]
Done. Feel free to open follow up issues. :)

**Pull request closed without merging**
