### PR TITLE
Fix problems with success_cmd on windows nvim.

### PR DESCRIPTION
**Pull request by Nicholas42**
Applied changes as suggested by @yongrenjie in #2084

### CODE REVIEW

**Comment by yongrenjie** [comment]
I think, just to be safe, I should check what happens if `&shell` is different from the default, since that may affect how the command string is quoted... I'll do that when I can...

**Comment by Nicholas42** [comment]
Yes, that seems like a good idea. One could also think about a parameter en/disabling this since it seems to be very fragile and not *that* important (though, personally I like it very much).

**Comment by yongrenjie** [comment]
Yeah, sadly, adding

```vim
set shell=powershell
set shellcmdflag=-command
```

to `init.vim` gives this error

```
At line:1 char:13
+ "cmd /s /c "set max_print_line=2000 & latexmk -verbose -file-line-err ...
+             ~~~
Unexpected token 'set' in expression or statement.
At line:1 char:37
+ "cmd /s /c "set max_print_line=2000 & latexmk -verbose -file-line-err ...
+                                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 ```

But this ampersand is already part of the existing code, and wasn't introduced by this PR. So it's probably not our/your problem to fix. :-)

**Comment by yongrenjie** [comment]
And I just noticed `:h vimtex-faq-windows` says to not change `&shell` anyway, so I guess that's not really a problem.

**Comment by lervag** [comment]
Thanks for this, and for the discussion. As I'm not a Windows user, I really do depend on the contribution of others to help make VimTeX work well on Windows as well - it is much appreciated!

**Comment by lervag** [comment]
Please note I also made a simple adjustment; see here:

https://github.com/lervag/vimtex/blob/c1e02461f5ccb15892bf8ce21d41f7fcac33d0db/autoload/vimtex/compiler/latexmk.vim#L628-L638

I believe this should still work and I think it is slightly more readable. I also believe the comment makes more sense now. Can you confirm?

**Comment by lervag** [comment]
Please note I also made a simple adjustment; see here:

https://github.com/lervag/vimtex/blob/c1e02461f5ccb15892bf8ce21d41f7fcac33d0db/autoload/vimtex/compiler/latexmk.vim#L628-L638

I believe this should still work and I think it is slightly more readable. I also believe the comment makes more sense now. Can you confirm?

**Pull request closed without merging**
