### PR TITLE
escape path in MuPDF reverse search function

### PR DESCRIPTION
**Pull request by lahwaacz**
Fixed just a small bug I found when the path contained spaces...

### CODE REVIEW

**Comment by lervag** [comment]
Thanks! I didn't accept the pull request because I wanted to use the vimtex utility function `vimtex#util#fnameescape` instead, in order to also support windows.

**Comment by lahwaacz** [comment]
In that case, although I don't fully understand the difference, `fnameescape` is still used at multiple places. No idea if `vimtex#util#fnameescape` should be used everywhere or not...
```
$ grep -F ". fnameescape(" **/*.vim
autoload/vimtex/complete.vim:  execute 'lcd ' . fnameescape(b:vimtex.root)
autoload/vimtex/complete.vim:  execute 'lcd ' . fnameescape(l:save_pwd)
autoload/vimtex/index.vim:    execute 'badd ' . fnameescape(entry.file)
autoload/vimtex/latexmk.vim:    execute 'cfile ' . fnameescape(log)
autoload/vimtex/latexmk.vim:    execute 'cgetfile ' . fnameescape(log)
autoload/vimtex/util.vim:    execute 'lcd ' . fnameescape(a:exe.wd)
autoload/vimtex/util.vim:    execute 'lcd ' . fnameescape(pwd)
```

**Comment by micbou** [comment]
No, `vimtex#util#fnameescape` cannot be used for Vim commands. Commit a5531c7 breaks things for MuPDF users. The issue is that paths in Vim command cannot be escaped the same way as paths in the shell.

I think the function `vimtex#util#fnameescape` should be renamed to `vimtex#util#shellescape` to avoid confusion with `fnameescape` and should only be used for shell command. Always use `fnameescape` for Vim commands.

**Comment by lervag** [comment]
@micbou You are right! I don't know why I've mixed these functions (i.e. `fnameescape` and `shellescape`), but that is what I've done.

I'm updating as you recommend, changing `...fnameescape` to `...shellescape`.

If you find examples where I've mixed the `shellescape` with `fnameescape`, please let me know. I've looked through the code, but I couldn't find any more errors. I wouldn't be surprised if I've missed anything, though.

**Comment by micbou** [comment]
I didn't find any misuse of `vimtex#util#shellescape` and `fnameescape` but I found 3 `shellescape` that could certainly be replaced by `vimtex#util#shellescape`.

**Comment by lervag** [comment]
Thanks!

**Pull request closed without merging**
