### PR TITLE
Implement section text object

### LINKED ISSUE #687: Add new text object: section (subsection, subsubsection, etc)
### Explain the issue
There are following text objects at the moment:
```
  - ic ac Commands
  - id ad Delimiters
  - ie ae LaTeX environments              
  - i$ a$ Inline math structures   
```
I propose to add one more:
```
  - is as Sections (Subsections, Subsubsections, etc)
```

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\section

La-la-la

\subsection

----- Begin of subsection

some text 
----> CURSOR POSITION

\subsubsection
----- End of subsection
\subsection
La-la-la

\end{document}
```

I want `vis` to select text from `----- Begin of subsection` to `----- End of subsection`.

It is usually very useful text object (for example when you want to change notion inside one section)

### PR DESCRIPTION
**Pull request by lervag**
This is the first version of a sections text object. The PR fixes #687. See that issue for the feature description.

### CODE REVIEW

**Comment by kiryph** [comment]
Demo tex file:
```tex
\documentclass{article}

\begin{document}

\part{Part A}

\chapter{First Chapter}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\section{Section}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\subsection{Subsection}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\paragraph{Paragraph}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\part{Part B}

the next part

\end{document}
```

My first two observations are:

1. `viP` and `vaP` select also `\end{document}` when the cursor is in part B. Is this intentional?
2.  I miss again the extending the selection with `vaPaP`. For example when I am in the paragraph but I want to select the current section I would like to use `vaPaP` to get this.

**Comment by lervag** [comment]
This is harder than I expected, but I think I've solved most of the problems now. Please test.

**Comment by kiryph** [comment]
@lervag Did you push anything after my comment from yesterday?

**Comment by lervag** [comment]
Yes. A lot. But I rebased, so you must do a hard reset on the branch.

**Comment by kiryph** [comment]
This looks good.

Should the user be able to adjust which section commands are considered similar to `g:vimtex_fold_sections`?

**Comment by lervag** [comment]
I was thinking not. Instead, this should "just work". Or do you think this is something people would want to customize?

**Comment by lervag** [comment]
@petRUShka I think this PR now brings the feature you asked for in #687. Let me know what you think.

**Comment by kiryph** [comment]
I was asking because right now `\(sub)*paragraph` are ignored. I am not sure but I would expect that they can also be addressed. I would add them. Maybe @petRUShka can also say what he would expect.

Just for verification in the MWE by petRUShka `viP` does what has been asked:

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\section

La-la-la

\subsection

----- Begin of subsection

some text 
----> CURSOR POSITION

\subsubsection
----- End of subsection
\subsection
La-la-la

\end{document}
```

**Comment by lervag** [comment]
I never intended to ignore paragraphs and subparagraphs. Updating now.

**Comment by petRUShka** [comment]
@lervag , yes! Fully. I'm sorry I was out of discussion for a while.

**Comment by petRUShka** [comment]
I'll test it slightly later!

**Comment by lervag** [comment]
No problem! I think we are close to ready for merge, but I'll wait for some more testing.

**Comment by lervag** [comment]
I think this is ready for merge. If I hear nothing I'll merge it on Sunday.

**Pull request merged**
