### PR TITLE
Add label numbering to ToC

### PR DESCRIPTION
**Pull request by lervag**
This is a first version of an implementation for #1395 (see also #1191). Things seem to work well.

@clason 
@zhuosongz

### CODE REVIEW

**Comment by clason** [comment]
Very nice! I almost didn't notice it worked since the split is too narrow on my terminal -- maybe it makes sense to increase the width if the labels are shown?

**Comment by lervag** [comment]
> The performance difference can be notable, though -- for my usual stress test project, it's 25s with labels vs. 5s without (on first call, after that it's instant thanks to caching). For "normal" projects it makes almost no difference, though.

Ah, yes, this is not so unexpected. I've tried to improve this by only loading the label dictionary once, instead of each time the parser function for label entries is called. It might improve things notably.

> Very nice! I almost didn't notice it worked since the split is too narrow on my terminal -- maybe it makes sense to increase the width if the labels are shown?

Yes, I could use `winwidth()` in the `printf` expression. Will push an update for this soon. Let me know what you think.

**Comment by clason** [comment]
> Ah, yes, this is not so unexpected. I've tried to improve this by only loading the label dictionary once, instead of each time the parser function for label entries is called. It might improve things notably.

Yes, now it's down to 4-5s again 👍

> Yes, I could use winwidth() in the printf expression. Will push an update for this soon. Let me know what you think.

Hmm, this didn't change the width of the toc for me, but it does remove the spaces (and alignment) between the labels and the formatted references?

**Comment by lervag** [comment]
> Hmm, this didn't change the width of the toc for me, but it does remove the spaces (and alignment) between the labels and the formatted references?

Ah, I misunderstood you. The width of the toc window is specified by `g:vimtex_toc_config`, specifically the `split_width` key. See the docs. Personally, I prefer to use `split_pos` equal to `full`, as I only use the toc for navigation (I don't keep it open anyway).

**Comment by clason** [comment]
> Ah, I misunderstood you. The width of the toc window is specified by g:vimtex_toc_config, specifically the split_width key. See the docs. Personally, I prefer to use split_pos equal to full, as I only use the toc for navigation (I don't keep it open anyway).

Oh, right, should have read the doc 🤦 That's a good point! (Still think the default could be increased a bit :))

**Comment by lervag** [comment]
Yes, I could increase the default. Noone has suggested it before, but I guess 30 characters is somewhat "thin" for this kind of window.

**Comment by clason** [comment]
Especially now that it also shows the numbers. Not critical though, I just wanted to point out that you're hiding a shiny new feature ;)

**Comment by lervag** [comment]
Ok, I've merged this now. Feel free to open issues if you find any!

**Comment by lervag** [comment]
> Especially now that it also shows the numbers. Not critical though, I just wanted to point out that you're hiding a shiny new feature ;)

Thanks! I've changed to width 50, I think that should be better.

**Pull request merged**
