### PR TITLE
Completion source for LaTeX commands

### PR DESCRIPTION
**Pull request by lervag**
Adds a completion source for LaTeX commands. Very simple implementation, but should still be pretty useful.

When finished, this should solve #650.

### CODE REVIEW

**Comment by lervag** [comment]
Ok, so now it remains to generate good command completion sources. I think perhaps it is not desirable to include every imaginable command. Instead, I think, it would be more useful to only have the most relevant commands. Or, what do you guys think?

@kiryph @poppyschmo

Note: The current implementation supports:

- Loading class sources (prefixed with `class-`) and package sources
- `#include:` to include nested packages/classes
- Adding a mode indicator (this probably needs adjustment/improvement)
- Adds indicator to the completion menu about the package provider

The complete file syntax is this:

```
# include: package
command[ mode]
...
```

Here the mode string is not necessary, and if it is not provided, the command is completed in both normal and math mode.

The implementation lacks unicode symbols. I don't see how to add that in a simple manner. But if you guys would help me to generate the source files, then we could define a syntax such as this:

```
command, mode, symbol
```

Or perhaps there is a way to "infer" the symbol based on the command name?

Note: I've decided _not_ to use the `cwl` files directly, because they include very much more than just simply the command names. Even though it is some work to convert the `cwl` files to vimtex, I think it is worth the effort. But I also question the necessity of adding every possible command, and not just the frequently used ones.

**Comment by kiryph** [comment]
Is there a possibility to setup neocomplete with this?

Regarding the conversion of latex commands to unicode. Following scripts might be helpful to create these files:

- http://mirrors.ctan.org/macros/latex/contrib/unicode-math/unicode-math-table.tex
- https://code.google.com/archive/p/unicodeitlinux/
- https://github.com/vikhyat/latex-to-unicode

`\right` and pressing `ctrl-x ctrl-o` shows me also candidates which do not start with `right`. I am not sure whether I like this. I think I appreciate this behaviour for citations.

**Comment by lervag** [comment]
I use this to setup neocomplete (note the last line that will match commands):

```vim
let g:neocomplete#sources#omni#input_patterns.tex =
      \ '\v\\%('
      \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
      \ . '|hyperref\s*\[[^]]*'
      \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|%(include%(only)?|input)\s*\{[^}]*'
      \ . '|usepackage%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|documentclass%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|\a*'
      \ . ')'
```

I'll look into your suggested links for unicode conversion. Also, I agree that for this completion type, we should anchor the regex. I'm updating and pushing now.

**Comment by kiryph** [comment]
I miss the completion of `\includegraphics` from https://cgit.kde.org/kile.git/plain/src/data/complete/tex/graphicx.cwl

demo-complete

**Comment by poppyschmo** [comment]
The symbol stuff is pretty trivial. [This `.json` file](https://github.com/poppyschmo/deoplete-latex/blob/master/rplugin/python3/deoplete/resources/latest.json) includes most of the common unicode glyphs. Also, many of [these scripts](https://github.com/poppyschmo/deoplete-latex/tree/master/rplugin/python3/deoplete/resources) were made expressly to scrape various sources for these same symbols, though with more of an eye toward the "web"/js side of things.

**Comment by lervag** [comment]
Thanks, @poppyschmo! I already figured out a lot of this stuff myself, e.g. from [this SO post](http://tex.stackexchange.com/questions/162385/an-extensive-list-of-latex-symbols-and-unicode-equivalents). Do you have any idea if your sources are better than the method from that post?

**Comment by lervag** [comment]
Ok, I ended up combining symbols from several sources. I also made a script to add symbols to complete files. In any case, the current version should also show symbols when available.

**Comment by lervag** [comment]
The question now is: Is the feature appropriate in itself? In that case, I propose to clean up and merge, independently from working on improved sources for command completion.

**Comment by lervag** [comment]
Ok, I've ended up writing a parser for the `cwl` files and generated completion files based on `texstudio`s cwl files. I think we now have a large set of completion candidates, as well as symbols for most (relevant) commands.

What is lacking now is mode specific completion, but I think this should be fine for now.

If someone would be willing to learn the format of the cwl files from texstudio and explain how to parse the mode specifiers, then I could try to parse that as well and add mode specific command completion.

**Comment by lervag** [comment]
I've merged this now. Feel free to open new issues, I think there are several things that can be improved still.

**Pull request closed without merging**
