### PR TITLE
qf: Add vbox support

### PR DESCRIPTION
**Pull request by mgelde**
Add support for overfull/underfull vboxes in QuickFix window (as opposed
to the already supported hboxes).

### CODE REVIEW

**Comment by lervag** [comment]
Hmm. I can't remember having seen those warnings before. Could you also add an example, either as a comment here or in `test/issues/1228`?

**Comment by mgelde** [comment]
Sorry, I did not get around to putting up a MWE (which was surprisingly hard, given that I see these in beamer presentations fairly often)...

```
\documentclass{beamer}                                                                                                                                                                                              
\begin{document}                                                                                    
                                                                                                    
\begin{frame}                                                                                       
Bla                                                                                                 
\begin{minipage}[c][50cm][c]{2cm}                                                                   
    \begin{tabular}{c}                                                                              
        a\\b\\c                                                                                     
    \end{tabular}                                                                                   
\end{minipage}\\                                                                                    
Bla                                                                                                 
\end{frame}                                                                                         
\end{document}
```
Produces (pdflatex and xelatex tested): ``Overfull \vbox (1163.09532pt too high) detected at line 12``

**Comment by mgelde** [comment]
Accidentally closed this PR... Sorry.

**Comment by lervag** [comment]
Thank you for this!

**Pull request merged**
