### PR TITLE
Improved syntax highlighting for bib files

### PR DESCRIPTION
**Pull request by danielbmarques**
This adds syntax highlighting for all the entry types and field types
used by biblatex.

### CODE REVIEW

**Comment by lervag** [comment]
Interesting. However, I think this would be better to include in the internal `bib.vim` syntax file, see `:e $VIMRUNTIME/syntax/bib.vim`. At least, I propose that you email Bernd Feige first. If he does not want to include your updates, I will consider to add it to vimtex.

**Comment by lervag** [comment]
By the way, I would be happy if you could squash the commits. You can do this with

```sh
git rebase -i
git push -f
```

In the rebase, use the `fixup` option on the last commit (or the `squash` if you want to change the commit message).

**Comment by danielbmarques** [comment]
Ok, I wrote to him, I'll let you know what he says.

Also I tried the squashing thing but couldn't work it out, I'm still getting the hang of git, sorry.
Is this what I was supposed to do?

captura de tela 2016-05-29 as 19 40 42
captura de tela 2016-05-29 as 19 41 20

I tried some other variations, but it seems it didn't work.

**Comment by lervag** [comment]
Sorry, I should have written that you should do:

```sh
git rebase -i 257d2f9
```

Since you've already pushed the branch, it will not automatically define which commits to rebase, thus you have to specify it. 257d2f9 is the hash for the corresponding master branch, and so this will start an interactive rebase session for all commits in your branch. Now you can chosse to "fixup" the typo commit.

**Comment by danielbmarques** [comment]
Ah, ok, now I got it, thanks. :)
But Bernd Feige just answered me and he is going to add the new keywords to the internal file, so I guess we can close this anyway.

**Comment by lervag** [comment]
No problem! And I'm happy to hear Bernd Feige accepted the changes. I think this is a more appropriate solution that will benefit _all_ LaTeX users, regardless of whether or not they use vimtex.

Thanks!

**Pull request closed without merging**
