### PR TITLE
add commands to embed files from `:VimtexIssue`

### PR DESCRIPTION
**Pull request by 927589452**
this is a work in progress

### CODE REVIEW

**Comment by 927589452** [comment]
this is for #1463

**Comment by 927589452** [comment]
I am reading the `autoload/vimtex/info.vim`, but I don't know how to get the return values of the internal commands.
maybe a public function wrapping the inner lines of the print statement, which can be used inside the template to get the lines and inside the print statement to append them

**Comment by lervag** [comment]
> I am reading the autoload/vimtex/info.vim, but I don't know how to get the return values of the internal commands.

Not quite sure what you mean.

> maybe a public function wrapping the inner lines of the print statement, which can be used inside the template to get the lines and inside the print statement to append them

An example could perhaps help make it clearer what you mean?

**Comment by 927589452** [comment]
> > I am reading the autoload/vimtex/info.vim, but I don't know how to get the return values of the internal commands.
> 
> Not quite sure what you mean.
> 
> > maybe a public function wrapping the inner lines of the print statement, which can be used inside the template to get the lines and inside the print statement to append them
> 
> An example could perhaps help make it clearer what you mean?

If I understood correctly, the output of `VimtexInfo` is assembled directly in the buffer, but I wanted to do a `<ESC>:read VimtexInfoOutput`, so it could be easily embedded in the document.
But while thinkig about it, I just realized a `VimtexInfoInsert` inserting the output into the current buffer could work too

**Comment by lervag** [comment]
I really have to admit I don't quite understand how this should work. I think I might have mentioned it before, but I propose that before you try to implement anything, you should write the documentation. This would make it easier for me to understand what you want to achieve, and it would be easier to help.

**Comment by lervag** [comment]
I'm closing due to lack of activity, but please feel free to reopen if you want to continue the discussion/idea!

**Pull request closed without merging**
