### PR TITLE
Interference between vimtex#cmd#create_ask and indent module

### PR DESCRIPTION
**Pull request by Aster89**
The insertion of `}` before `{` caused an unwanted indent reduction, which resulted in the first char of last visual selection to move rightward and, consequently, in the insertion of the `\command{` in the wrong place.

### CODE REVIEW

**Comment by lervag** [comment]
This seems good, but I won't merge as is. If I did, I would include a lot of unnecessary commits. Please either let me add this manually myself, or update the PR (or open a new) where you remove the unnecessary commits.

E.g., from your local repo:

```sh
git checkout master
git pull  # In case you have not already done so
git checkout -b some-branch-name master

# Do the changes

git commit ...
git push -u origin some-branch-name  # Push to your github fork
```

Now, on your github for you can open a clean PR.

Note, though, that it seems you have "messed up" your master branch. Thus I think the best approach either now (or in future PRs) is to create a clean fork, and then follow the above procedure. If you do, then you can always keep your local master branch on your fork up to date with the vimtex master, which makes it easy to create new branches for new PRs.

I hope this makes sense...

**Comment by lervag** [comment]
If you find this cumbersome, I can review your changes and add them manually, with the cost that your name will not be attached to the commit itself. I'll reference this PR in my commit message. However, you could also view this as an opportunitty to learn some more about how to use git..?

**Comment by Aster89** [comment]
I made as you aked (in particular I deleted my fork and builded it again), and send a new, clean [PR](https://github.com/lervag/vimtex/pull/699).

**Comment by lervag** [comment]
Thanks!

**Pull request closed without merging**
